package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.BloodMatchingAction;

public interface BloodMatchingActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_BloodMatching
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_BloodMatching
     *
     * @mbggenerated
     */
    int insert(BloodMatchingAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_BloodMatching
     *
     * @mbggenerated
     */
    int insertSelective(BloodMatchingAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_BloodMatching
     *
     * @mbggenerated
     */
    BloodMatchingAction selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_BloodMatching
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BloodMatchingAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_BloodMatching
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BloodMatchingAction record);
}