package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.Diet;

public interface DietMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Inst_Diet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Inst_Diet
     *
     * @mbggenerated
     */
    int insert(Diet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Inst_Diet
     *
     * @mbggenerated
     */
    int insertSelective(Diet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Inst_Diet
     *
     * @mbggenerated
     */
    Diet selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Inst_Diet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Diet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Inst_Diet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Diet record);
}