package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.DrugDispenseReqStatus;

public interface DrugDispenseReqStatusMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_DispensingDrugs
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_DispensingDrugs
	 * @mbggenerated
	 */
	int insert(DrugDispenseReqStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_DispensingDrugs
	 * @mbggenerated
	 */
	int insertSelective(DrugDispenseReqStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_DispensingDrugs
	 * @mbggenerated
	 */
	DrugDispenseReqStatus selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_DispensingDrugs
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DrugDispenseReqStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_DispensingDrugs
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DrugDispenseReqStatus record);
}