package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.ExamStatus;

public interface ExamStatusMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_ImagingExamination
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_ImagingExamination
	 * @mbggenerated
	 */
	int insert(ExamStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_ImagingExamination
	 * @mbggenerated
	 */
	int insertSelective(ExamStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_ImagingExamination
	 * @mbggenerated
	 */
	ExamStatus selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_ImagingExamination
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ExamStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_ImagingExamination
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ExamStatus record);
}