package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.ExamReqInfo;

public interface ExamReqInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Inst_ImagingExaminationRequest
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Inst_ImagingExaminationRequest
	 * @mbggenerated
	 */
	int insert(ExamReqInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Inst_ImagingExaminationRequest
	 * @mbggenerated
	 */
	int insertSelective(ExamReqInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Inst_ImagingExaminationRequest
	 * @mbggenerated
	 */
	ExamReqInfo selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Inst_ImagingExaminationRequest
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ExamReqInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Inst_ImagingExaminationRequest
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ExamReqInfo record);
}