package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.LabTestData;

public interface LabTestDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_LaboratoryTest
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_LaboratoryTest
     *
     * @mbggenerated
     */
    int insert(LabTestData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_LaboratoryTest
     *
     * @mbggenerated
     */
    int insertSelective(LabTestData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_LaboratoryTest
     *
     * @mbggenerated
     */
    LabTestData selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_LaboratoryTest
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LabTestData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_LaboratoryTest
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LabTestData record);
}