package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.LabTestStatus;

public interface LabTestStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_LabTest
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_LabTest
     *
     * @mbggenerated
     */
    int insert(LabTestStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_LabTest
     *
     * @mbggenerated
     */
    int insertSelective(LabTestStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_LabTest
     *
     * @mbggenerated
     */
    LabTestStatus selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_LabTest
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LabTestStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_LabTest
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LabTestStatus record);
}