package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.ManagementAction;

public interface ManagementActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Management
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Management
     *
     * @mbggenerated
     */
    int insert(ManagementAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Management
     *
     * @mbggenerated
     */
    int insertSelective(ManagementAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Management
     *
     * @mbggenerated
     */
    ManagementAction selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Management
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManagementAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Management
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManagementAction record);
}