package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.NewBornExamination;

public interface NewBornExaminationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn_ExaminationAfterBirth
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn_ExaminationAfterBirth
     *
     * @mbggenerated
     */
    int insert(NewBornExamination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn_ExaminationAfterBirth
     *
     * @mbggenerated
     */
    int insertSelective(NewBornExamination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn_ExaminationAfterBirth
     *
     * @mbggenerated
     */
    NewBornExamination selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn_ExaminationAfterBirth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewBornExamination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn_ExaminationAfterBirth
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewBornExamination record);
}