package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.NewBornMaster;

public interface NewBornMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn
     *
     * @mbggenerated
     */
    int insert(NewBornMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn
     *
     * @mbggenerated
     */
    int insertSelective(NewBornMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn
     *
     * @mbggenerated
     */
    NewBornMaster selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewBornMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewBornMaster record);
}