package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.NewBornOtherInformation;

public interface NewBornOtherInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn_OtherInformation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn_OtherInformation
     *
     * @mbggenerated
     */
    int insert(NewBornOtherInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn_OtherInformation
     *
     * @mbggenerated
     */
    int insertSelective(NewBornOtherInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn_OtherInformation
     *
     * @mbggenerated
     */
    NewBornOtherInformation selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn_OtherInformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewBornOtherInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Obsr_NewBorn_OtherInformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewBornOtherInformation record);
}