package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.OrderExecutePaperStatus;

public interface OrderExecutePaperStatusMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_OrderExcute
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_OrderExcute
	 * @mbggenerated
	 */
	int insert(OrderExecutePaperStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_OrderExcute
	 * @mbggenerated
	 */
	int insertSelective(OrderExecutePaperStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_OrderExcute
	 * @mbggenerated
	 */
	OrderExecutePaperStatus selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_OrderExcute
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(OrderExecutePaperStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_OrderExcute
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OrderExecutePaperStatus record);
}