package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.PatientVisitInfo;

public interface PatientVisitInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Admin_PatientAdmission
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Admin_PatientAdmission
	 * @mbggenerated
	 */
	int insert(PatientVisitInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Admin_PatientAdmission
	 * @mbggenerated
	 */
	int insertSelective(PatientVisitInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Admin_PatientAdmission
	 * @mbggenerated
	 */
	PatientVisitInfo selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Admin_PatientAdmission
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PatientVisitInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Admin_PatientAdmission
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PatientVisitInfo record);
}