package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.Remain;

public interface RemainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Inst_Remain
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Inst_Remain
     *
     * @mbggenerated
     */
    int insert(Remain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Inst_Remain
     *
     * @mbggenerated
     */
    int insertSelective(Remain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Inst_Remain
     *
     * @mbggenerated
     */
    Remain selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Inst_Remain
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Remain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Inst_Remain
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Remain record);
}