package com.vico.clever.cdr.service.dao;

import com.vico.clever.cdr.service.model.TransfusionAction;

public interface TransfusionActionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_Transfusion
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_Transfusion
	 * @mbggenerated
	 */
	int insert(TransfusionAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_Transfusion
	 * @mbggenerated
	 */
	int insertSelective(TransfusionAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_Transfusion
	 * @mbggenerated
	 */
	TransfusionAction selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_Transfusion
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(TransfusionAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Action_Transfusion
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TransfusionAction record);
}