package com.test.ssm.model;

public class PatientInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.PATIENTID
     *
     * @mbggenerated
     */
    private String patientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.PATIENTNAME
     *
     * @mbggenerated
     */
    private String patientname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.ID
     *
     * @return the value of PATIENT.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.ID
     *
     * @param id the value for PATIENT.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.PATIENTID
     *
     * @return the value of PATIENT.PATIENTID
     *
     * @mbggenerated
     */
    public String getPatientid() {
        return patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.PATIENTID
     *
     * @param patientid the value for PATIENT.PATIENTID
     *
     * @mbggenerated
     */
    public void setPatientid(String patientid) {
        this.patientid = patientid == null ? null : patientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.PATIENTNAME
     *
     * @return the value of PATIENT.PATIENTNAME
     *
     * @mbggenerated
     */
    public String getPatientname() {
        return patientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.PATIENTNAME
     *
     * @param patientname the value for PATIENT.PATIENTNAME
     *
     * @mbggenerated
     */
    public void setPatientname(String patientname) {
        this.patientname = patientname == null ? null : patientname.trim();
    }
}