package com.vico.clever.cdr.service.model;

import java.util.Date;

public class BloodMatching {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_BloodMatching.Guid
     *
     * @mbggenerated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_BloodMatching.Administration_Code
     *
     * @mbggenerated
     */
    private String administrationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_BloodMatching.Administration_Name
     *
     * @mbggenerated
     */
    private String administrationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_BloodMatching.BloodMatchingContent
     *
     * @mbggenerated
     */
    private String bloodmatchingcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_BloodMatching.BloodMatchingIdentifier
     *
     * @mbggenerated
     */
    private String bloodmatchingidentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_BloodMatching.DosageUnit
     *
     * @mbggenerated
     */
    private String dosageunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_BloodMatching.Dosage
     *
     * @mbggenerated
     */
    private String dosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_BloodMatching.EncounterIdentifier
     *
     * @mbggenerated
     */
    private String encounteridentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_BloodMatching.Memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_BloodMatching.OrderIdentifier
     *
     * @mbggenerated
     */
    private String orderidentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_BloodMatching.PatientIdentifier_Id
     *
     * @mbggenerated
     */
    private String patientidentifierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_BloodMatching.PlannedExecDatetime
     *
     * @mbggenerated
     */
    private Date plannedexecdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_BloodMatching.PlannedStopDatetime
     *
     * @mbggenerated
     */
    private Date plannedstopdatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_BloodMatching.Guid
     *
     * @return the value of Inst_BloodMatching.Guid
     *
     * @mbggenerated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_BloodMatching.Guid
     *
     * @param guid the value for Inst_BloodMatching.Guid
     *
     * @mbggenerated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_BloodMatching.Administration_Code
     *
     * @return the value of Inst_BloodMatching.Administration_Code
     *
     * @mbggenerated
     */
    public String getAdministrationCode() {
        return administrationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_BloodMatching.Administration_Code
     *
     * @param administrationCode the value for Inst_BloodMatching.Administration_Code
     *
     * @mbggenerated
     */
    public void setAdministrationCode(String administrationCode) {
        this.administrationCode = administrationCode == null ? null : administrationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_BloodMatching.Administration_Name
     *
     * @return the value of Inst_BloodMatching.Administration_Name
     *
     * @mbggenerated
     */
    public String getAdministrationName() {
        return administrationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_BloodMatching.Administration_Name
     *
     * @param administrationName the value for Inst_BloodMatching.Administration_Name
     *
     * @mbggenerated
     */
    public void setAdministrationName(String administrationName) {
        this.administrationName = administrationName == null ? null : administrationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_BloodMatching.BloodMatchingContent
     *
     * @return the value of Inst_BloodMatching.BloodMatchingContent
     *
     * @mbggenerated
     */
    public String getBloodmatchingcontent() {
        return bloodmatchingcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_BloodMatching.BloodMatchingContent
     *
     * @param bloodmatchingcontent the value for Inst_BloodMatching.BloodMatchingContent
     *
     * @mbggenerated
     */
    public void setBloodmatchingcontent(String bloodmatchingcontent) {
        this.bloodmatchingcontent = bloodmatchingcontent == null ? null : bloodmatchingcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_BloodMatching.BloodMatchingIdentifier
     *
     * @return the value of Inst_BloodMatching.BloodMatchingIdentifier
     *
     * @mbggenerated
     */
    public String getBloodmatchingidentifier() {
        return bloodmatchingidentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_BloodMatching.BloodMatchingIdentifier
     *
     * @param bloodmatchingidentifier the value for Inst_BloodMatching.BloodMatchingIdentifier
     *
     * @mbggenerated
     */
    public void setBloodmatchingidentifier(String bloodmatchingidentifier) {
        this.bloodmatchingidentifier = bloodmatchingidentifier == null ? null : bloodmatchingidentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_BloodMatching.DosageUnit
     *
     * @return the value of Inst_BloodMatching.DosageUnit
     *
     * @mbggenerated
     */
    public String getDosageunit() {
        return dosageunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_BloodMatching.DosageUnit
     *
     * @param dosageunit the value for Inst_BloodMatching.DosageUnit
     *
     * @mbggenerated
     */
    public void setDosageunit(String dosageunit) {
        this.dosageunit = dosageunit == null ? null : dosageunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_BloodMatching.Dosage
     *
     * @return the value of Inst_BloodMatching.Dosage
     *
     * @mbggenerated
     */
    public String getDosage() {
        return dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_BloodMatching.Dosage
     *
     * @param dosage the value for Inst_BloodMatching.Dosage
     *
     * @mbggenerated
     */
    public void setDosage(String dosage) {
        this.dosage = dosage == null ? null : dosage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_BloodMatching.EncounterIdentifier
     *
     * @return the value of Inst_BloodMatching.EncounterIdentifier
     *
     * @mbggenerated
     */
    public String getEncounteridentifier() {
        return encounteridentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_BloodMatching.EncounterIdentifier
     *
     * @param encounteridentifier the value for Inst_BloodMatching.EncounterIdentifier
     *
     * @mbggenerated
     */
    public void setEncounteridentifier(String encounteridentifier) {
        this.encounteridentifier = encounteridentifier == null ? null : encounteridentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_BloodMatching.Memo
     *
     * @return the value of Inst_BloodMatching.Memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_BloodMatching.Memo
     *
     * @param memo the value for Inst_BloodMatching.Memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_BloodMatching.OrderIdentifier
     *
     * @return the value of Inst_BloodMatching.OrderIdentifier
     *
     * @mbggenerated
     */
    public String getOrderidentifier() {
        return orderidentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_BloodMatching.OrderIdentifier
     *
     * @param orderidentifier the value for Inst_BloodMatching.OrderIdentifier
     *
     * @mbggenerated
     */
    public void setOrderidentifier(String orderidentifier) {
        this.orderidentifier = orderidentifier == null ? null : orderidentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_BloodMatching.PatientIdentifier_Id
     *
     * @return the value of Inst_BloodMatching.PatientIdentifier_Id
     *
     * @mbggenerated
     */
    public String getPatientidentifierId() {
        return patientidentifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_BloodMatching.PatientIdentifier_Id
     *
     * @param patientidentifierId the value for Inst_BloodMatching.PatientIdentifier_Id
     *
     * @mbggenerated
     */
    public void setPatientidentifierId(String patientidentifierId) {
        this.patientidentifierId = patientidentifierId == null ? null : patientidentifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_BloodMatching.PlannedExecDatetime
     *
     * @return the value of Inst_BloodMatching.PlannedExecDatetime
     *
     * @mbggenerated
     */
    public Date getPlannedexecdatetime() {
        return plannedexecdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_BloodMatching.PlannedExecDatetime
     *
     * @param plannedexecdatetime the value for Inst_BloodMatching.PlannedExecDatetime
     *
     * @mbggenerated
     */
    public void setPlannedexecdatetime(Date plannedexecdatetime) {
        this.plannedexecdatetime = plannedexecdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_BloodMatching.PlannedStopDatetime
     *
     * @return the value of Inst_BloodMatching.PlannedStopDatetime
     *
     * @mbggenerated
     */
    public Date getPlannedstopdatetime() {
        return plannedstopdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_BloodMatching.PlannedStopDatetime
     *
     * @param plannedstopdatetime the value for Inst_BloodMatching.PlannedStopDatetime
     *
     * @mbggenerated
     */
    public void setPlannedstopdatetime(Date plannedstopdatetime) {
        this.plannedstopdatetime = plannedstopdatetime;
    }
}