package com.vico.clever.cdr.service.model;

public class DispensingDrugsReq {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.Guid
	 * @mbggenerated
	 */
	private String guid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.ApprovalNumber
	 * @mbggenerated
	 */
	private String approvalnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.BatchId
	 * @mbggenerated
	 */
	private String batchid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.DestinationPharmacy_Code
	 * @mbggenerated
	 */
	private String destinationpharmacyCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.DestinationPharmacy_Name
	 * @mbggenerated
	 */
	private String destinationpharmacyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.DrugsDispensingRequestIdentifier
	 * @mbggenerated
	 */
	private String drugsdispensingrequestidentifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.Emergency
	 * @mbggenerated
	 */
	private String emergency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.EncounterIdentifier
	 * @mbggenerated
	 */
	private String encounteridentifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.Manufacturer
	 * @mbggenerated
	 */
	private String manufacturer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.MedicationInstructionId
	 * @mbggenerated
	 */
	private String medicationinstructionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.PatientIdentifier_Id
	 * @mbggenerated
	 */
	private String patientidentifierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.ReceiveDispensingAmountUnit
	 * @mbggenerated
	 */
	private String receivedispensingamountunit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.ReceiveDispensingAmount
	 * @mbggenerated
	 */
	private String receivedispensingamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.RequestDepartment_Code
	 * @mbggenerated
	 */
	private String requestdepartmentCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.RequestDepartment_Name
	 * @mbggenerated
	 */
	private String requestdepartmentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.RequestDispensingAmountUnit
	 * @mbggenerated
	 */
	private String requestdispensingamountunit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.RequestDispensingAmount
	 * @mbggenerated
	 */
	private String requestdispensingamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.TradeName
	 * @mbggenerated
	 */
	private String tradename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.RequestWard_Code
	 * @mbggenerated
	 */
	private String requestwardCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_DrugsDispensing.RequestWard_Name
	 * @mbggenerated
	 */
	private String requestwardName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.Guid
	 * @return  the value of Inst_DrugsDispensing.Guid
	 * @mbggenerated
	 */
	public String getGuid() {
		return guid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.Guid
	 * @param guid  the value for Inst_DrugsDispensing.Guid
	 * @mbggenerated
	 */
	public void setGuid(String guid) {
		this.guid = guid == null ? null : guid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.ApprovalNumber
	 * @return  the value of Inst_DrugsDispensing.ApprovalNumber
	 * @mbggenerated
	 */
	public String getApprovalnumber() {
		return approvalnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.ApprovalNumber
	 * @param approvalnumber  the value for Inst_DrugsDispensing.ApprovalNumber
	 * @mbggenerated
	 */
	public void setApprovalnumber(String approvalnumber) {
		this.approvalnumber = approvalnumber == null ? null : approvalnumber
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.BatchId
	 * @return  the value of Inst_DrugsDispensing.BatchId
	 * @mbggenerated
	 */
	public String getBatchid() {
		return batchid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.BatchId
	 * @param batchid  the value for Inst_DrugsDispensing.BatchId
	 * @mbggenerated
	 */
	public void setBatchid(String batchid) {
		this.batchid = batchid == null ? null : batchid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.DestinationPharmacy_Code
	 * @return  the value of Inst_DrugsDispensing.DestinationPharmacy_Code
	 * @mbggenerated
	 */
	public String getDestinationpharmacyCode() {
		return destinationpharmacyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.DestinationPharmacy_Code
	 * @param destinationpharmacyCode  the value for Inst_DrugsDispensing.DestinationPharmacy_Code
	 * @mbggenerated
	 */
	public void setDestinationpharmacyCode(String destinationpharmacyCode) {
		this.destinationpharmacyCode = destinationpharmacyCode == null ? null
				: destinationpharmacyCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.DestinationPharmacy_Name
	 * @return  the value of Inst_DrugsDispensing.DestinationPharmacy_Name
	 * @mbggenerated
	 */
	public String getDestinationpharmacyName() {
		return destinationpharmacyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.DestinationPharmacy_Name
	 * @param destinationpharmacyName  the value for Inst_DrugsDispensing.DestinationPharmacy_Name
	 * @mbggenerated
	 */
	public void setDestinationpharmacyName(String destinationpharmacyName) {
		this.destinationpharmacyName = destinationpharmacyName == null ? null
				: destinationpharmacyName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.DrugsDispensingRequestIdentifier
	 * @return  the value of Inst_DrugsDispensing.DrugsDispensingRequestIdentifier
	 * @mbggenerated
	 */
	public String getDrugsdispensingrequestidentifier() {
		return drugsdispensingrequestidentifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.DrugsDispensingRequestIdentifier
	 * @param drugsdispensingrequestidentifier  the value for Inst_DrugsDispensing.DrugsDispensingRequestIdentifier
	 * @mbggenerated
	 */
	public void setDrugsdispensingrequestidentifier(
			String drugsdispensingrequestidentifier) {
		this.drugsdispensingrequestidentifier = drugsdispensingrequestidentifier == null ? null
				: drugsdispensingrequestidentifier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.Emergency
	 * @return  the value of Inst_DrugsDispensing.Emergency
	 * @mbggenerated
	 */
	public String getEmergency() {
		return emergency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.Emergency
	 * @param emergency  the value for Inst_DrugsDispensing.Emergency
	 * @mbggenerated
	 */
	public void setEmergency(String emergency) {
		this.emergency = emergency == null ? null : emergency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.EncounterIdentifier
	 * @return  the value of Inst_DrugsDispensing.EncounterIdentifier
	 * @mbggenerated
	 */
	public String getEncounteridentifier() {
		return encounteridentifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.EncounterIdentifier
	 * @param encounteridentifier  the value for Inst_DrugsDispensing.EncounterIdentifier
	 * @mbggenerated
	 */
	public void setEncounteridentifier(String encounteridentifier) {
		this.encounteridentifier = encounteridentifier == null ? null
				: encounteridentifier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.Manufacturer
	 * @return  the value of Inst_DrugsDispensing.Manufacturer
	 * @mbggenerated
	 */
	public String getManufacturer() {
		return manufacturer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.Manufacturer
	 * @param manufacturer  the value for Inst_DrugsDispensing.Manufacturer
	 * @mbggenerated
	 */
	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer == null ? null : manufacturer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.MedicationInstructionId
	 * @return  the value of Inst_DrugsDispensing.MedicationInstructionId
	 * @mbggenerated
	 */
	public String getMedicationinstructionid() {
		return medicationinstructionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.MedicationInstructionId
	 * @param medicationinstructionid  the value for Inst_DrugsDispensing.MedicationInstructionId
	 * @mbggenerated
	 */
	public void setMedicationinstructionid(String medicationinstructionid) {
		this.medicationinstructionid = medicationinstructionid == null ? null
				: medicationinstructionid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.PatientIdentifier_Id
	 * @return  the value of Inst_DrugsDispensing.PatientIdentifier_Id
	 * @mbggenerated
	 */
	public String getPatientidentifierId() {
		return patientidentifierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.PatientIdentifier_Id
	 * @param patientidentifierId  the value for Inst_DrugsDispensing.PatientIdentifier_Id
	 * @mbggenerated
	 */
	public void setPatientidentifierId(String patientidentifierId) {
		this.patientidentifierId = patientidentifierId == null ? null
				: patientidentifierId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.ReceiveDispensingAmountUnit
	 * @return  the value of Inst_DrugsDispensing.ReceiveDispensingAmountUnit
	 * @mbggenerated
	 */
	public String getReceivedispensingamountunit() {
		return receivedispensingamountunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.ReceiveDispensingAmountUnit
	 * @param receivedispensingamountunit  the value for Inst_DrugsDispensing.ReceiveDispensingAmountUnit
	 * @mbggenerated
	 */
	public void setReceivedispensingamountunit(
			String receivedispensingamountunit) {
		this.receivedispensingamountunit = receivedispensingamountunit == null ? null
				: receivedispensingamountunit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.ReceiveDispensingAmount
	 * @return  the value of Inst_DrugsDispensing.ReceiveDispensingAmount
	 * @mbggenerated
	 */
	public String getReceivedispensingamount() {
		return receivedispensingamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.ReceiveDispensingAmount
	 * @param receivedispensingamount  the value for Inst_DrugsDispensing.ReceiveDispensingAmount
	 * @mbggenerated
	 */
	public void setReceivedispensingamount(String receivedispensingamount) {
		this.receivedispensingamount = receivedispensingamount == null ? null
				: receivedispensingamount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.RequestDepartment_Code
	 * @return  the value of Inst_DrugsDispensing.RequestDepartment_Code
	 * @mbggenerated
	 */
	public String getRequestdepartmentCode() {
		return requestdepartmentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.RequestDepartment_Code
	 * @param requestdepartmentCode  the value for Inst_DrugsDispensing.RequestDepartment_Code
	 * @mbggenerated
	 */
	public void setRequestdepartmentCode(String requestdepartmentCode) {
		this.requestdepartmentCode = requestdepartmentCode == null ? null
				: requestdepartmentCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.RequestDepartment_Name
	 * @return  the value of Inst_DrugsDispensing.RequestDepartment_Name
	 * @mbggenerated
	 */
	public String getRequestdepartmentName() {
		return requestdepartmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.RequestDepartment_Name
	 * @param requestdepartmentName  the value for Inst_DrugsDispensing.RequestDepartment_Name
	 * @mbggenerated
	 */
	public void setRequestdepartmentName(String requestdepartmentName) {
		this.requestdepartmentName = requestdepartmentName == null ? null
				: requestdepartmentName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.RequestDispensingAmountUnit
	 * @return  the value of Inst_DrugsDispensing.RequestDispensingAmountUnit
	 * @mbggenerated
	 */
	public String getRequestdispensingamountunit() {
		return requestdispensingamountunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.RequestDispensingAmountUnit
	 * @param requestdispensingamountunit  the value for Inst_DrugsDispensing.RequestDispensingAmountUnit
	 * @mbggenerated
	 */
	public void setRequestdispensingamountunit(
			String requestdispensingamountunit) {
		this.requestdispensingamountunit = requestdispensingamountunit == null ? null
				: requestdispensingamountunit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.RequestDispensingAmount
	 * @return  the value of Inst_DrugsDispensing.RequestDispensingAmount
	 * @mbggenerated
	 */
	public String getRequestdispensingamount() {
		return requestdispensingamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.RequestDispensingAmount
	 * @param requestdispensingamount  the value for Inst_DrugsDispensing.RequestDispensingAmount
	 * @mbggenerated
	 */
	public void setRequestdispensingamount(String requestdispensingamount) {
		this.requestdispensingamount = requestdispensingamount == null ? null
				: requestdispensingamount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.TradeName
	 * @return  the value of Inst_DrugsDispensing.TradeName
	 * @mbggenerated
	 */
	public String getTradename() {
		return tradename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.TradeName
	 * @param tradename  the value for Inst_DrugsDispensing.TradeName
	 * @mbggenerated
	 */
	public void setTradename(String tradename) {
		this.tradename = tradename == null ? null : tradename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.RequestWard_Code
	 * @return  the value of Inst_DrugsDispensing.RequestWard_Code
	 * @mbggenerated
	 */
	public String getRequestwardCode() {
		return requestwardCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.RequestWard_Code
	 * @param requestwardCode  the value for Inst_DrugsDispensing.RequestWard_Code
	 * @mbggenerated
	 */
	public void setRequestwardCode(String requestwardCode) {
		this.requestwardCode = requestwardCode == null ? null : requestwardCode
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_DrugsDispensing.RequestWard_Name
	 * @return  the value of Inst_DrugsDispensing.RequestWard_Name
	 * @mbggenerated
	 */
	public String getRequestwardName() {
		return requestwardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_DrugsDispensing.RequestWard_Name
	 * @param requestwardName  the value for Inst_DrugsDispensing.RequestWard_Name
	 * @mbggenerated
	 */
	public void setRequestwardName(String requestwardName) {
		this.requestwardName = requestwardName == null ? null : requestwardName
				.trim();
	}
}