package com.vico.clever.cdr.service.model;

import java.util.Date;

public class LabTestItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.Guid
     *
     * @mbggenerated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.Inst_LaboratoryTestRequest$Guid
     *
     * @mbggenerated
     */
    private String instLaboratorytestrequestGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.DescriptionOfService
     *
     * @mbggenerated
     */
    private String descriptionofservice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.Inst_LaboratoryTestRequest$RequestorIdentifier
     *
     * @mbggenerated
     */
    private String instLaboratorytestrequestRequestoridentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.ItemNumber
     *
     * @mbggenerated
     */
    private String itemnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.ServiceClass_Code
     *
     * @mbggenerated
     */
    private String serviceclassCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.ServiceClass_Name
     *
     * @mbggenerated
     */
    private String serviceclassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.ServiceRequested
     *
     * @mbggenerated
     */
    private String servicerequested;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_CollectionAndHandling_TransportMedium_Code
     *
     * @mbggenerated
     */
    private String specimendetailsCollectionandhandlingTransportmediumCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_CollectionAndHandling_TransportMedium_Name
     *
     * @mbggenerated
     */
    private String specimendetailsCollectionandhandlingTransportmediumName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_HandlingAndProcessing_DateAndTimeOfCollection
     *
     * @mbggenerated
     */
    private Date specimendetailsHandlingandprocessingDateandtimeofcollection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_HandlingAndProcessing_DateAndTimeOfReceipt
     *
     * @mbggenerated
     */
    private Date specimendetailsHandlingandprocessingDateandtimeofreceipt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_Identifiers_SpecimenIdentifier
     *
     * @mbggenerated
     */
    private String specimendetailsIdentifiersSpecimenidentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_SpecimenTissueType_Code
     *
     * @mbggenerated
     */
    private String specimendetailsSpecimentissuetypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_SpecimenTissueType_Name
     *
     * @mbggenerated
     */
    private String specimendetailsSpecimentissuetypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_Status
     *
     * @mbggenerated
     */
    private String specimendetailsStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.Guid
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.Guid
     *
     * @mbggenerated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.Guid
     *
     * @param guid the value for Inst_LaboratoryTestRequest_TestItem.Guid
     *
     * @mbggenerated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.Inst_LaboratoryTestRequest$Guid
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.Inst_LaboratoryTestRequest$Guid
     *
     * @mbggenerated
     */
    public String getInstLaboratorytestrequestGuid() {
        return instLaboratorytestrequestGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.Inst_LaboratoryTestRequest$Guid
     *
     * @param instLaboratorytestrequestGuid the value for Inst_LaboratoryTestRequest_TestItem.Inst_LaboratoryTestRequest$Guid
     *
     * @mbggenerated
     */
    public void setInstLaboratorytestrequestGuid(String instLaboratorytestrequestGuid) {
        this.instLaboratorytestrequestGuid = instLaboratorytestrequestGuid == null ? null : instLaboratorytestrequestGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.DescriptionOfService
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.DescriptionOfService
     *
     * @mbggenerated
     */
    public String getDescriptionofservice() {
        return descriptionofservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.DescriptionOfService
     *
     * @param descriptionofservice the value for Inst_LaboratoryTestRequest_TestItem.DescriptionOfService
     *
     * @mbggenerated
     */
    public void setDescriptionofservice(String descriptionofservice) {
        this.descriptionofservice = descriptionofservice == null ? null : descriptionofservice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.Inst_LaboratoryTestRequest$RequestorIdentifier
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.Inst_LaboratoryTestRequest$RequestorIdentifier
     *
     * @mbggenerated
     */
    public String getInstLaboratorytestrequestRequestoridentifier() {
        return instLaboratorytestrequestRequestoridentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.Inst_LaboratoryTestRequest$RequestorIdentifier
     *
     * @param instLaboratorytestrequestRequestoridentifier the value for Inst_LaboratoryTestRequest_TestItem.Inst_LaboratoryTestRequest$RequestorIdentifier
     *
     * @mbggenerated
     */
    public void setInstLaboratorytestrequestRequestoridentifier(String instLaboratorytestrequestRequestoridentifier) {
        this.instLaboratorytestrequestRequestoridentifier = instLaboratorytestrequestRequestoridentifier == null ? null : instLaboratorytestrequestRequestoridentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.ItemNumber
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.ItemNumber
     *
     * @mbggenerated
     */
    public String getItemnumber() {
        return itemnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.ItemNumber
     *
     * @param itemnumber the value for Inst_LaboratoryTestRequest_TestItem.ItemNumber
     *
     * @mbggenerated
     */
    public void setItemnumber(String itemnumber) {
        this.itemnumber = itemnumber == null ? null : itemnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.ServiceClass_Code
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.ServiceClass_Code
     *
     * @mbggenerated
     */
    public String getServiceclassCode() {
        return serviceclassCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.ServiceClass_Code
     *
     * @param serviceclassCode the value for Inst_LaboratoryTestRequest_TestItem.ServiceClass_Code
     *
     * @mbggenerated
     */
    public void setServiceclassCode(String serviceclassCode) {
        this.serviceclassCode = serviceclassCode == null ? null : serviceclassCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.ServiceClass_Name
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.ServiceClass_Name
     *
     * @mbggenerated
     */
    public String getServiceclassName() {
        return serviceclassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.ServiceClass_Name
     *
     * @param serviceclassName the value for Inst_LaboratoryTestRequest_TestItem.ServiceClass_Name
     *
     * @mbggenerated
     */
    public void setServiceclassName(String serviceclassName) {
        this.serviceclassName = serviceclassName == null ? null : serviceclassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.ServiceRequested
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.ServiceRequested
     *
     * @mbggenerated
     */
    public String getServicerequested() {
        return servicerequested;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.ServiceRequested
     *
     * @param servicerequested the value for Inst_LaboratoryTestRequest_TestItem.ServiceRequested
     *
     * @mbggenerated
     */
    public void setServicerequested(String servicerequested) {
        this.servicerequested = servicerequested == null ? null : servicerequested.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_CollectionAndHandling_TransportMedium_Code
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_CollectionAndHandling_TransportMedium_Code
     *
     * @mbggenerated
     */
    public String getSpecimendetailsCollectionandhandlingTransportmediumCode() {
        return specimendetailsCollectionandhandlingTransportmediumCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_CollectionAndHandling_TransportMedium_Code
     *
     * @param specimendetailsCollectionandhandlingTransportmediumCode the value for Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_CollectionAndHandling_TransportMedium_Code
     *
     * @mbggenerated
     */
    public void setSpecimendetailsCollectionandhandlingTransportmediumCode(String specimendetailsCollectionandhandlingTransportmediumCode) {
        this.specimendetailsCollectionandhandlingTransportmediumCode = specimendetailsCollectionandhandlingTransportmediumCode == null ? null : specimendetailsCollectionandhandlingTransportmediumCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_CollectionAndHandling_TransportMedium_Name
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_CollectionAndHandling_TransportMedium_Name
     *
     * @mbggenerated
     */
    public String getSpecimendetailsCollectionandhandlingTransportmediumName() {
        return specimendetailsCollectionandhandlingTransportmediumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_CollectionAndHandling_TransportMedium_Name
     *
     * @param specimendetailsCollectionandhandlingTransportmediumName the value for Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_CollectionAndHandling_TransportMedium_Name
     *
     * @mbggenerated
     */
    public void setSpecimendetailsCollectionandhandlingTransportmediumName(String specimendetailsCollectionandhandlingTransportmediumName) {
        this.specimendetailsCollectionandhandlingTransportmediumName = specimendetailsCollectionandhandlingTransportmediumName == null ? null : specimendetailsCollectionandhandlingTransportmediumName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_HandlingAndProcessing_DateAndTimeOfCollection
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_HandlingAndProcessing_DateAndTimeOfCollection
     *
     * @mbggenerated
     */
    public Date getSpecimendetailsHandlingandprocessingDateandtimeofcollection() {
        return specimendetailsHandlingandprocessingDateandtimeofcollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_HandlingAndProcessing_DateAndTimeOfCollection
     *
     * @param specimendetailsHandlingandprocessingDateandtimeofcollection the value for Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_HandlingAndProcessing_DateAndTimeOfCollection
     *
     * @mbggenerated
     */
    public void setSpecimendetailsHandlingandprocessingDateandtimeofcollection(Date specimendetailsHandlingandprocessingDateandtimeofcollection) {
        this.specimendetailsHandlingandprocessingDateandtimeofcollection = specimendetailsHandlingandprocessingDateandtimeofcollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_HandlingAndProcessing_DateAndTimeOfReceipt
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_HandlingAndProcessing_DateAndTimeOfReceipt
     *
     * @mbggenerated
     */
    public Date getSpecimendetailsHandlingandprocessingDateandtimeofreceipt() {
        return specimendetailsHandlingandprocessingDateandtimeofreceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_HandlingAndProcessing_DateAndTimeOfReceipt
     *
     * @param specimendetailsHandlingandprocessingDateandtimeofreceipt the value for Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_HandlingAndProcessing_DateAndTimeOfReceipt
     *
     * @mbggenerated
     */
    public void setSpecimendetailsHandlingandprocessingDateandtimeofreceipt(Date specimendetailsHandlingandprocessingDateandtimeofreceipt) {
        this.specimendetailsHandlingandprocessingDateandtimeofreceipt = specimendetailsHandlingandprocessingDateandtimeofreceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_Identifiers_SpecimenIdentifier
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_Identifiers_SpecimenIdentifier
     *
     * @mbggenerated
     */
    public String getSpecimendetailsIdentifiersSpecimenidentifier() {
        return specimendetailsIdentifiersSpecimenidentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_Identifiers_SpecimenIdentifier
     *
     * @param specimendetailsIdentifiersSpecimenidentifier the value for Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_Identifiers_SpecimenIdentifier
     *
     * @mbggenerated
     */
    public void setSpecimendetailsIdentifiersSpecimenidentifier(String specimendetailsIdentifiersSpecimenidentifier) {
        this.specimendetailsIdentifiersSpecimenidentifier = specimendetailsIdentifiersSpecimenidentifier == null ? null : specimendetailsIdentifiersSpecimenidentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_SpecimenTissueType_Code
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_SpecimenTissueType_Code
     *
     * @mbggenerated
     */
    public String getSpecimendetailsSpecimentissuetypeCode() {
        return specimendetailsSpecimentissuetypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_SpecimenTissueType_Code
     *
     * @param specimendetailsSpecimentissuetypeCode the value for Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_SpecimenTissueType_Code
     *
     * @mbggenerated
     */
    public void setSpecimendetailsSpecimentissuetypeCode(String specimendetailsSpecimentissuetypeCode) {
        this.specimendetailsSpecimentissuetypeCode = specimendetailsSpecimentissuetypeCode == null ? null : specimendetailsSpecimentissuetypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_SpecimenTissueType_Name
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_SpecimenTissueType_Name
     *
     * @mbggenerated
     */
    public String getSpecimendetailsSpecimentissuetypeName() {
        return specimendetailsSpecimentissuetypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_SpecimenTissueType_Name
     *
     * @param specimendetailsSpecimentissuetypeName the value for Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_SpecimenTissueType_Name
     *
     * @mbggenerated
     */
    public void setSpecimendetailsSpecimentissuetypeName(String specimendetailsSpecimentissuetypeName) {
        this.specimendetailsSpecimentissuetypeName = specimendetailsSpecimentissuetypeName == null ? null : specimendetailsSpecimentissuetypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_Status
     *
     * @return the value of Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_Status
     *
     * @mbggenerated
     */
    public String getSpecimendetailsStatus() {
        return specimendetailsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_Status
     *
     * @param specimendetailsStatus the value for Inst_LaboratoryTestRequest_TestItem.SpecimenDetails_Status
     *
     * @mbggenerated
     */
    public void setSpecimendetailsStatus(String specimendetailsStatus) {
        this.specimendetailsStatus = specimendetailsStatus == null ? null : specimendetailsStatus.trim();
    }
}