package com.vico.clever.cdr.service.model;

import java.util.Date;

public class NewBornExamination {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Guid
     *
     * @mbggenerated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Obsr_NewBorn$Guid
     *
     * @mbggenerated
     */
    private String obsrNewbornGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Anus
     *
     * @mbggenerated
     */
    private String anus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.ArmsAndLegs
     *
     * @mbggenerated
     */
    private String armsandlegs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Bpd
     *
     * @mbggenerated
     */
    private String bpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Cc
     *
     * @mbggenerated
     */
    private String cc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.CreateDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Creator_Code
     *
     * @mbggenerated
     */
    private String creatorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Creator_Name
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Ear
     *
     * @mbggenerated
     */
    private String ear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Eye
     *
     * @mbggenerated
     */
    private String eye;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Genitals
     *
     * @mbggenerated
     */
    private String genitals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Hc
     *
     * @mbggenerated
     */
    private String hc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Heart
     *
     * @mbggenerated
     */
    private String heart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.LastModifiedDate
     *
     * @mbggenerated
     */
    private Date lastmodifieddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.LastModifier_Code
     *
     * @mbggenerated
     */
    private String lastmodifierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.LastModifier_Name
     *
     * @mbggenerated
     */
    private String lastmodifierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Lip
     *
     * @mbggenerated
     */
    private String lip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Liver
     *
     * @mbggenerated
     */
    private String liver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Lung
     *
     * @mbggenerated
     */
    private String lung;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Nose
     *
     * @mbggenerated
     */
    private String nose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Obsr_NewBorn$NewBornIdentifier
     *
     * @mbggenerated
     */
    private String obsrNewbornNewbornidentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Ofc
     *
     * @mbggenerated
     */
    private String ofc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Ofd
     *
     * @mbggenerated
     */
    private String ofd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Omd
     *
     * @mbggenerated
     */
    private String omd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.OtherOrgan
     *
     * @mbggenerated
     */
    private String otherorgan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Sbc
     *
     * @mbggenerated
     */
    private String sbc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Sbd
     *
     * @mbggenerated
     */
    private String sbd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.Spleen
     *
     * @mbggenerated
     */
    private String spleen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_ExaminationAfterBirth.UmbilicalCord
     *
     * @mbggenerated
     */
    private String umbilicalcord;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Guid
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Guid
     *
     * @mbggenerated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Guid
     *
     * @param guid the value for Obsr_NewBorn_ExaminationAfterBirth.Guid
     *
     * @mbggenerated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Obsr_NewBorn$Guid
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Obsr_NewBorn$Guid
     *
     * @mbggenerated
     */
    public String getObsrNewbornGuid() {
        return obsrNewbornGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Obsr_NewBorn$Guid
     *
     * @param obsrNewbornGuid the value for Obsr_NewBorn_ExaminationAfterBirth.Obsr_NewBorn$Guid
     *
     * @mbggenerated
     */
    public void setObsrNewbornGuid(String obsrNewbornGuid) {
        this.obsrNewbornGuid = obsrNewbornGuid == null ? null : obsrNewbornGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Anus
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Anus
     *
     * @mbggenerated
     */
    public String getAnus() {
        return anus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Anus
     *
     * @param anus the value for Obsr_NewBorn_ExaminationAfterBirth.Anus
     *
     * @mbggenerated
     */
    public void setAnus(String anus) {
        this.anus = anus == null ? null : anus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.ArmsAndLegs
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.ArmsAndLegs
     *
     * @mbggenerated
     */
    public String getArmsandlegs() {
        return armsandlegs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.ArmsAndLegs
     *
     * @param armsandlegs the value for Obsr_NewBorn_ExaminationAfterBirth.ArmsAndLegs
     *
     * @mbggenerated
     */
    public void setArmsandlegs(String armsandlegs) {
        this.armsandlegs = armsandlegs == null ? null : armsandlegs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Bpd
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Bpd
     *
     * @mbggenerated
     */
    public String getBpd() {
        return bpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Bpd
     *
     * @param bpd the value for Obsr_NewBorn_ExaminationAfterBirth.Bpd
     *
     * @mbggenerated
     */
    public void setBpd(String bpd) {
        this.bpd = bpd == null ? null : bpd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Cc
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Cc
     *
     * @mbggenerated
     */
    public String getCc() {
        return cc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Cc
     *
     * @param cc the value for Obsr_NewBorn_ExaminationAfterBirth.Cc
     *
     * @mbggenerated
     */
    public void setCc(String cc) {
        this.cc = cc == null ? null : cc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.CreateDate
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.CreateDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.CreateDate
     *
     * @param createdate the value for Obsr_NewBorn_ExaminationAfterBirth.CreateDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Creator_Code
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Creator_Code
     *
     * @mbggenerated
     */
    public String getCreatorCode() {
        return creatorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Creator_Code
     *
     * @param creatorCode the value for Obsr_NewBorn_ExaminationAfterBirth.Creator_Code
     *
     * @mbggenerated
     */
    public void setCreatorCode(String creatorCode) {
        this.creatorCode = creatorCode == null ? null : creatorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Creator_Name
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Creator_Name
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Creator_Name
     *
     * @param creatorName the value for Obsr_NewBorn_ExaminationAfterBirth.Creator_Name
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Ear
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Ear
     *
     * @mbggenerated
     */
    public String getEar() {
        return ear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Ear
     *
     * @param ear the value for Obsr_NewBorn_ExaminationAfterBirth.Ear
     *
     * @mbggenerated
     */
    public void setEar(String ear) {
        this.ear = ear == null ? null : ear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Eye
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Eye
     *
     * @mbggenerated
     */
    public String getEye() {
        return eye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Eye
     *
     * @param eye the value for Obsr_NewBorn_ExaminationAfterBirth.Eye
     *
     * @mbggenerated
     */
    public void setEye(String eye) {
        this.eye = eye == null ? null : eye.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Genitals
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Genitals
     *
     * @mbggenerated
     */
    public String getGenitals() {
        return genitals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Genitals
     *
     * @param genitals the value for Obsr_NewBorn_ExaminationAfterBirth.Genitals
     *
     * @mbggenerated
     */
    public void setGenitals(String genitals) {
        this.genitals = genitals == null ? null : genitals.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Hc
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Hc
     *
     * @mbggenerated
     */
    public String getHc() {
        return hc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Hc
     *
     * @param hc the value for Obsr_NewBorn_ExaminationAfterBirth.Hc
     *
     * @mbggenerated
     */
    public void setHc(String hc) {
        this.hc = hc == null ? null : hc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Heart
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Heart
     *
     * @mbggenerated
     */
    public String getHeart() {
        return heart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Heart
     *
     * @param heart the value for Obsr_NewBorn_ExaminationAfterBirth.Heart
     *
     * @mbggenerated
     */
    public void setHeart(String heart) {
        this.heart = heart == null ? null : heart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.LastModifiedDate
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.LastModifiedDate
     *
     * @mbggenerated
     */
    public Date getLastmodifieddate() {
        return lastmodifieddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.LastModifiedDate
     *
     * @param lastmodifieddate the value for Obsr_NewBorn_ExaminationAfterBirth.LastModifiedDate
     *
     * @mbggenerated
     */
    public void setLastmodifieddate(Date lastmodifieddate) {
        this.lastmodifieddate = lastmodifieddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.LastModifier_Code
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.LastModifier_Code
     *
     * @mbggenerated
     */
    public String getLastmodifierCode() {
        return lastmodifierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.LastModifier_Code
     *
     * @param lastmodifierCode the value for Obsr_NewBorn_ExaminationAfterBirth.LastModifier_Code
     *
     * @mbggenerated
     */
    public void setLastmodifierCode(String lastmodifierCode) {
        this.lastmodifierCode = lastmodifierCode == null ? null : lastmodifierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.LastModifier_Name
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.LastModifier_Name
     *
     * @mbggenerated
     */
    public String getLastmodifierName() {
        return lastmodifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.LastModifier_Name
     *
     * @param lastmodifierName the value for Obsr_NewBorn_ExaminationAfterBirth.LastModifier_Name
     *
     * @mbggenerated
     */
    public void setLastmodifierName(String lastmodifierName) {
        this.lastmodifierName = lastmodifierName == null ? null : lastmodifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Lip
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Lip
     *
     * @mbggenerated
     */
    public String getLip() {
        return lip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Lip
     *
     * @param lip the value for Obsr_NewBorn_ExaminationAfterBirth.Lip
     *
     * @mbggenerated
     */
    public void setLip(String lip) {
        this.lip = lip == null ? null : lip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Liver
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Liver
     *
     * @mbggenerated
     */
    public String getLiver() {
        return liver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Liver
     *
     * @param liver the value for Obsr_NewBorn_ExaminationAfterBirth.Liver
     *
     * @mbggenerated
     */
    public void setLiver(String liver) {
        this.liver = liver == null ? null : liver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Lung
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Lung
     *
     * @mbggenerated
     */
    public String getLung() {
        return lung;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Lung
     *
     * @param lung the value for Obsr_NewBorn_ExaminationAfterBirth.Lung
     *
     * @mbggenerated
     */
    public void setLung(String lung) {
        this.lung = lung == null ? null : lung.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Nose
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Nose
     *
     * @mbggenerated
     */
    public String getNose() {
        return nose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Nose
     *
     * @param nose the value for Obsr_NewBorn_ExaminationAfterBirth.Nose
     *
     * @mbggenerated
     */
    public void setNose(String nose) {
        this.nose = nose == null ? null : nose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Obsr_NewBorn$NewBornIdentifier
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Obsr_NewBorn$NewBornIdentifier
     *
     * @mbggenerated
     */
    public String getObsrNewbornNewbornidentifier() {
        return obsrNewbornNewbornidentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Obsr_NewBorn$NewBornIdentifier
     *
     * @param obsrNewbornNewbornidentifier the value for Obsr_NewBorn_ExaminationAfterBirth.Obsr_NewBorn$NewBornIdentifier
     *
     * @mbggenerated
     */
    public void setObsrNewbornNewbornidentifier(String obsrNewbornNewbornidentifier) {
        this.obsrNewbornNewbornidentifier = obsrNewbornNewbornidentifier == null ? null : obsrNewbornNewbornidentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Ofc
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Ofc
     *
     * @mbggenerated
     */
    public String getOfc() {
        return ofc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Ofc
     *
     * @param ofc the value for Obsr_NewBorn_ExaminationAfterBirth.Ofc
     *
     * @mbggenerated
     */
    public void setOfc(String ofc) {
        this.ofc = ofc == null ? null : ofc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Ofd
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Ofd
     *
     * @mbggenerated
     */
    public String getOfd() {
        return ofd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Ofd
     *
     * @param ofd the value for Obsr_NewBorn_ExaminationAfterBirth.Ofd
     *
     * @mbggenerated
     */
    public void setOfd(String ofd) {
        this.ofd = ofd == null ? null : ofd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Omd
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Omd
     *
     * @mbggenerated
     */
    public String getOmd() {
        return omd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Omd
     *
     * @param omd the value for Obsr_NewBorn_ExaminationAfterBirth.Omd
     *
     * @mbggenerated
     */
    public void setOmd(String omd) {
        this.omd = omd == null ? null : omd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.OtherOrgan
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.OtherOrgan
     *
     * @mbggenerated
     */
    public String getOtherorgan() {
        return otherorgan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.OtherOrgan
     *
     * @param otherorgan the value for Obsr_NewBorn_ExaminationAfterBirth.OtherOrgan
     *
     * @mbggenerated
     */
    public void setOtherorgan(String otherorgan) {
        this.otherorgan = otherorgan == null ? null : otherorgan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Sbc
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Sbc
     *
     * @mbggenerated
     */
    public String getSbc() {
        return sbc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Sbc
     *
     * @param sbc the value for Obsr_NewBorn_ExaminationAfterBirth.Sbc
     *
     * @mbggenerated
     */
    public void setSbc(String sbc) {
        this.sbc = sbc == null ? null : sbc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Sbd
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Sbd
     *
     * @mbggenerated
     */
    public String getSbd() {
        return sbd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Sbd
     *
     * @param sbd the value for Obsr_NewBorn_ExaminationAfterBirth.Sbd
     *
     * @mbggenerated
     */
    public void setSbd(String sbd) {
        this.sbd = sbd == null ? null : sbd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Spleen
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.Spleen
     *
     * @mbggenerated
     */
    public String getSpleen() {
        return spleen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.Spleen
     *
     * @param spleen the value for Obsr_NewBorn_ExaminationAfterBirth.Spleen
     *
     * @mbggenerated
     */
    public void setSpleen(String spleen) {
        this.spleen = spleen == null ? null : spleen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_ExaminationAfterBirth.UmbilicalCord
     *
     * @return the value of Obsr_NewBorn_ExaminationAfterBirth.UmbilicalCord
     *
     * @mbggenerated
     */
    public String getUmbilicalcord() {
        return umbilicalcord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_ExaminationAfterBirth.UmbilicalCord
     *
     * @param umbilicalcord the value for Obsr_NewBorn_ExaminationAfterBirth.UmbilicalCord
     *
     * @mbggenerated
     */
    public void setUmbilicalcord(String umbilicalcord) {
        this.umbilicalcord = umbilicalcord == null ? null : umbilicalcord.trim();
    }
}