package com.vico.clever.cdr.service.model;

import java.util.Date;

public class NewBirthProcess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.Guid
     *
     * @mbggenerated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.Obsr_NewBorn$Guid
     *
     * @mbggenerated
     */
    private String obsrNewbornGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.CreateDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.Creator_Code
     *
     * @mbggenerated
     */
    private String creatorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.Creator_Name
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.DeliveryClass
     *
     * @mbggenerated
     */
    private String deliveryclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.DeliveryType
     *
     * @mbggenerated
     */
    private String deliverytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.DoctorOne_Code
     *
     * @mbggenerated
     */
    private String doctoroneCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.DoctorOne_Name
     *
     * @mbggenerated
     */
    private String doctoroneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.DoctorTwo_Code
     *
     * @mbggenerated
     */
    private String doctortwoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.DoctorTwo_Name
     *
     * @mbggenerated
     */
    private String doctortwoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.FetalLie
     *
     * @mbggenerated
     */
    private String fetallie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.FetalPosition
     *
     * @mbggenerated
     */
    private String fetalposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.FetalPresentation
     *
     * @mbggenerated
     */
    private String fetalpresentation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.GestationalDays
     *
     * @mbggenerated
     */
    private Integer gestationaldays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.GestationalWeeks
     *
     * @mbggenerated
     */
    private Integer gestationalweeks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.LastModifiedDate
     *
     * @mbggenerated
     */
    private Date lastmodifieddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.LastModifier_Code
     *
     * @mbggenerated
     */
    private String lastmodifierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.LastModifier_Name
     *
     * @mbggenerated
     */
    private String lastmodifierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.NurseOne_Code
     *
     * @mbggenerated
     */
    private String nurseoneCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.NurseOne_Name
     *
     * @mbggenerated
     */
    private String nurseoneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.NurseTwo_Code
     *
     * @mbggenerated
     */
    private String nursetwoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.NurseTwo_Name
     *
     * @mbggenerated
     */
    private String nursetwoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Obsr_NewBorn_BirthProcessSummary.Obsr_NewBorn$NewBornIdentifier
     *
     * @mbggenerated
     */
    private String obsrNewbornNewbornidentifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.Guid
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.Guid
     *
     * @mbggenerated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.Guid
     *
     * @param guid the value for Obsr_NewBorn_BirthProcessSummary.Guid
     *
     * @mbggenerated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.Obsr_NewBorn$Guid
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.Obsr_NewBorn$Guid
     *
     * @mbggenerated
     */
    public String getObsrNewbornGuid() {
        return obsrNewbornGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.Obsr_NewBorn$Guid
     *
     * @param obsrNewbornGuid the value for Obsr_NewBorn_BirthProcessSummary.Obsr_NewBorn$Guid
     *
     * @mbggenerated
     */
    public void setObsrNewbornGuid(String obsrNewbornGuid) {
        this.obsrNewbornGuid = obsrNewbornGuid == null ? null : obsrNewbornGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.CreateDate
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.CreateDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.CreateDate
     *
     * @param createdate the value for Obsr_NewBorn_BirthProcessSummary.CreateDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.Creator_Code
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.Creator_Code
     *
     * @mbggenerated
     */
    public String getCreatorCode() {
        return creatorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.Creator_Code
     *
     * @param creatorCode the value for Obsr_NewBorn_BirthProcessSummary.Creator_Code
     *
     * @mbggenerated
     */
    public void setCreatorCode(String creatorCode) {
        this.creatorCode = creatorCode == null ? null : creatorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.Creator_Name
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.Creator_Name
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.Creator_Name
     *
     * @param creatorName the value for Obsr_NewBorn_BirthProcessSummary.Creator_Name
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.DeliveryClass
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.DeliveryClass
     *
     * @mbggenerated
     */
    public String getDeliveryclass() {
        return deliveryclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.DeliveryClass
     *
     * @param deliveryclass the value for Obsr_NewBorn_BirthProcessSummary.DeliveryClass
     *
     * @mbggenerated
     */
    public void setDeliveryclass(String deliveryclass) {
        this.deliveryclass = deliveryclass == null ? null : deliveryclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.DeliveryType
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.DeliveryType
     *
     * @mbggenerated
     */
    public String getDeliverytype() {
        return deliverytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.DeliveryType
     *
     * @param deliverytype the value for Obsr_NewBorn_BirthProcessSummary.DeliveryType
     *
     * @mbggenerated
     */
    public void setDeliverytype(String deliverytype) {
        this.deliverytype = deliverytype == null ? null : deliverytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.DoctorOne_Code
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.DoctorOne_Code
     *
     * @mbggenerated
     */
    public String getDoctoroneCode() {
        return doctoroneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.DoctorOne_Code
     *
     * @param doctoroneCode the value for Obsr_NewBorn_BirthProcessSummary.DoctorOne_Code
     *
     * @mbggenerated
     */
    public void setDoctoroneCode(String doctoroneCode) {
        this.doctoroneCode = doctoroneCode == null ? null : doctoroneCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.DoctorOne_Name
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.DoctorOne_Name
     *
     * @mbggenerated
     */
    public String getDoctoroneName() {
        return doctoroneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.DoctorOne_Name
     *
     * @param doctoroneName the value for Obsr_NewBorn_BirthProcessSummary.DoctorOne_Name
     *
     * @mbggenerated
     */
    public void setDoctoroneName(String doctoroneName) {
        this.doctoroneName = doctoroneName == null ? null : doctoroneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.DoctorTwo_Code
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.DoctorTwo_Code
     *
     * @mbggenerated
     */
    public String getDoctortwoCode() {
        return doctortwoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.DoctorTwo_Code
     *
     * @param doctortwoCode the value for Obsr_NewBorn_BirthProcessSummary.DoctorTwo_Code
     *
     * @mbggenerated
     */
    public void setDoctortwoCode(String doctortwoCode) {
        this.doctortwoCode = doctortwoCode == null ? null : doctortwoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.DoctorTwo_Name
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.DoctorTwo_Name
     *
     * @mbggenerated
     */
    public String getDoctortwoName() {
        return doctortwoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.DoctorTwo_Name
     *
     * @param doctortwoName the value for Obsr_NewBorn_BirthProcessSummary.DoctorTwo_Name
     *
     * @mbggenerated
     */
    public void setDoctortwoName(String doctortwoName) {
        this.doctortwoName = doctortwoName == null ? null : doctortwoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.FetalLie
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.FetalLie
     *
     * @mbggenerated
     */
    public String getFetallie() {
        return fetallie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.FetalLie
     *
     * @param fetallie the value for Obsr_NewBorn_BirthProcessSummary.FetalLie
     *
     * @mbggenerated
     */
    public void setFetallie(String fetallie) {
        this.fetallie = fetallie == null ? null : fetallie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.FetalPosition
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.FetalPosition
     *
     * @mbggenerated
     */
    public String getFetalposition() {
        return fetalposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.FetalPosition
     *
     * @param fetalposition the value for Obsr_NewBorn_BirthProcessSummary.FetalPosition
     *
     * @mbggenerated
     */
    public void setFetalposition(String fetalposition) {
        this.fetalposition = fetalposition == null ? null : fetalposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.FetalPresentation
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.FetalPresentation
     *
     * @mbggenerated
     */
    public String getFetalpresentation() {
        return fetalpresentation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.FetalPresentation
     *
     * @param fetalpresentation the value for Obsr_NewBorn_BirthProcessSummary.FetalPresentation
     *
     * @mbggenerated
     */
    public void setFetalpresentation(String fetalpresentation) {
        this.fetalpresentation = fetalpresentation == null ? null : fetalpresentation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.GestationalDays
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.GestationalDays
     *
     * @mbggenerated
     */
    public Integer getGestationaldays() {
        return gestationaldays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.GestationalDays
     *
     * @param gestationaldays the value for Obsr_NewBorn_BirthProcessSummary.GestationalDays
     *
     * @mbggenerated
     */
    public void setGestationaldays(Integer gestationaldays) {
        this.gestationaldays = gestationaldays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.GestationalWeeks
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.GestationalWeeks
     *
     * @mbggenerated
     */
    public Integer getGestationalweeks() {
        return gestationalweeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.GestationalWeeks
     *
     * @param gestationalweeks the value for Obsr_NewBorn_BirthProcessSummary.GestationalWeeks
     *
     * @mbggenerated
     */
    public void setGestationalweeks(Integer gestationalweeks) {
        this.gestationalweeks = gestationalweeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.LastModifiedDate
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.LastModifiedDate
     *
     * @mbggenerated
     */
    public Date getLastmodifieddate() {
        return lastmodifieddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.LastModifiedDate
     *
     * @param lastmodifieddate the value for Obsr_NewBorn_BirthProcessSummary.LastModifiedDate
     *
     * @mbggenerated
     */
    public void setLastmodifieddate(Date lastmodifieddate) {
        this.lastmodifieddate = lastmodifieddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.LastModifier_Code
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.LastModifier_Code
     *
     * @mbggenerated
     */
    public String getLastmodifierCode() {
        return lastmodifierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.LastModifier_Code
     *
     * @param lastmodifierCode the value for Obsr_NewBorn_BirthProcessSummary.LastModifier_Code
     *
     * @mbggenerated
     */
    public void setLastmodifierCode(String lastmodifierCode) {
        this.lastmodifierCode = lastmodifierCode == null ? null : lastmodifierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.LastModifier_Name
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.LastModifier_Name
     *
     * @mbggenerated
     */
    public String getLastmodifierName() {
        return lastmodifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.LastModifier_Name
     *
     * @param lastmodifierName the value for Obsr_NewBorn_BirthProcessSummary.LastModifier_Name
     *
     * @mbggenerated
     */
    public void setLastmodifierName(String lastmodifierName) {
        this.lastmodifierName = lastmodifierName == null ? null : lastmodifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.NurseOne_Code
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.NurseOne_Code
     *
     * @mbggenerated
     */
    public String getNurseoneCode() {
        return nurseoneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.NurseOne_Code
     *
     * @param nurseoneCode the value for Obsr_NewBorn_BirthProcessSummary.NurseOne_Code
     *
     * @mbggenerated
     */
    public void setNurseoneCode(String nurseoneCode) {
        this.nurseoneCode = nurseoneCode == null ? null : nurseoneCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.NurseOne_Name
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.NurseOne_Name
     *
     * @mbggenerated
     */
    public String getNurseoneName() {
        return nurseoneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.NurseOne_Name
     *
     * @param nurseoneName the value for Obsr_NewBorn_BirthProcessSummary.NurseOne_Name
     *
     * @mbggenerated
     */
    public void setNurseoneName(String nurseoneName) {
        this.nurseoneName = nurseoneName == null ? null : nurseoneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.NurseTwo_Code
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.NurseTwo_Code
     *
     * @mbggenerated
     */
    public String getNursetwoCode() {
        return nursetwoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.NurseTwo_Code
     *
     * @param nursetwoCode the value for Obsr_NewBorn_BirthProcessSummary.NurseTwo_Code
     *
     * @mbggenerated
     */
    public void setNursetwoCode(String nursetwoCode) {
        this.nursetwoCode = nursetwoCode == null ? null : nursetwoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.NurseTwo_Name
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.NurseTwo_Name
     *
     * @mbggenerated
     */
    public String getNursetwoName() {
        return nursetwoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.NurseTwo_Name
     *
     * @param nursetwoName the value for Obsr_NewBorn_BirthProcessSummary.NurseTwo_Name
     *
     * @mbggenerated
     */
    public void setNursetwoName(String nursetwoName) {
        this.nursetwoName = nursetwoName == null ? null : nursetwoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Obsr_NewBorn_BirthProcessSummary.Obsr_NewBorn$NewBornIdentifier
     *
     * @return the value of Obsr_NewBorn_BirthProcessSummary.Obsr_NewBorn$NewBornIdentifier
     *
     * @mbggenerated
     */
    public String getObsrNewbornNewbornidentifier() {
        return obsrNewbornNewbornidentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Obsr_NewBorn_BirthProcessSummary.Obsr_NewBorn$NewBornIdentifier
     *
     * @param obsrNewbornNewbornidentifier the value for Obsr_NewBorn_BirthProcessSummary.Obsr_NewBorn$NewBornIdentifier
     *
     * @mbggenerated
     */
    public void setObsrNewbornNewbornidentifier(String obsrNewbornNewbornidentifier) {
        this.obsrNewbornNewbornidentifier = obsrNewbornNewbornidentifier == null ? null : obsrNewbornNewbornidentifier.trim();
    }
}