package com.vico.clever.cdr.service.model;

public class OrderInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_Order.Guid
	 * @mbggenerated
	 */
	private String guid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_Order.Emergency
	 * @mbggenerated
	 */
	private Boolean emergency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_Order.EncounterIdentifier
	 * @mbggenerated
	 */
	private String encounteridentifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_Order.MotherOrBaby
	 * @mbggenerated
	 */
	private String motherorbaby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_Order.OrderClass_Code
	 * @mbggenerated
	 */
	private String orderclassCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_Order.OrderClass_Name
	 * @mbggenerated
	 */
	private String orderclassName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_Order.OrderIdentifier
	 * @mbggenerated
	 */
	private String orderidentifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_Order.OrderNo
	 * @mbggenerated
	 */
	private String orderno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_Order.OrderSubNo
	 * @mbggenerated
	 */
	private String ordersubno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_Order.PatientIdentifier_Id
	 * @mbggenerated
	 */
	private String patientidentifierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_Order.RepeatOrder
	 * @mbggenerated
	 */
	private Boolean repeatorder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_Order.ReservedOrder
	 * @mbggenerated
	 */
	private Boolean reservedorder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Inst_Order.SubsequentOrder
	 * @mbggenerated
	 */
	private Boolean subsequentorder;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_Order.Guid
	 * @return  the value of Inst_Order.Guid
	 * @mbggenerated
	 */
	public String getGuid() {
		return guid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_Order.Guid
	 * @param guid  the value for Inst_Order.Guid
	 * @mbggenerated
	 */
	public void setGuid(String guid) {
		this.guid = guid == null ? null : guid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_Order.Emergency
	 * @return  the value of Inst_Order.Emergency
	 * @mbggenerated
	 */
	public Boolean getEmergency() {
		return emergency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_Order.Emergency
	 * @param emergency  the value for Inst_Order.Emergency
	 * @mbggenerated
	 */
	public void setEmergency(Boolean emergency) {
		this.emergency = emergency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_Order.EncounterIdentifier
	 * @return  the value of Inst_Order.EncounterIdentifier
	 * @mbggenerated
	 */
	public String getEncounteridentifier() {
		return encounteridentifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_Order.EncounterIdentifier
	 * @param encounteridentifier  the value for Inst_Order.EncounterIdentifier
	 * @mbggenerated
	 */
	public void setEncounteridentifier(String encounteridentifier) {
		this.encounteridentifier = encounteridentifier == null ? null
				: encounteridentifier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_Order.MotherOrBaby
	 * @return  the value of Inst_Order.MotherOrBaby
	 * @mbggenerated
	 */
	public String getMotherorbaby() {
		return motherorbaby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_Order.MotherOrBaby
	 * @param motherorbaby  the value for Inst_Order.MotherOrBaby
	 * @mbggenerated
	 */
	public void setMotherorbaby(String motherorbaby) {
		this.motherorbaby = motherorbaby == null ? null : motherorbaby.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_Order.OrderClass_Code
	 * @return  the value of Inst_Order.OrderClass_Code
	 * @mbggenerated
	 */
	public String getOrderclassCode() {
		return orderclassCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_Order.OrderClass_Code
	 * @param orderclassCode  the value for Inst_Order.OrderClass_Code
	 * @mbggenerated
	 */
	public void setOrderclassCode(String orderclassCode) {
		this.orderclassCode = orderclassCode == null ? null : orderclassCode
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_Order.OrderClass_Name
	 * @return  the value of Inst_Order.OrderClass_Name
	 * @mbggenerated
	 */
	public String getOrderclassName() {
		return orderclassName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_Order.OrderClass_Name
	 * @param orderclassName  the value for Inst_Order.OrderClass_Name
	 * @mbggenerated
	 */
	public void setOrderclassName(String orderclassName) {
		this.orderclassName = orderclassName == null ? null : orderclassName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_Order.OrderIdentifier
	 * @return  the value of Inst_Order.OrderIdentifier
	 * @mbggenerated
	 */
	public String getOrderidentifier() {
		return orderidentifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_Order.OrderIdentifier
	 * @param orderidentifier  the value for Inst_Order.OrderIdentifier
	 * @mbggenerated
	 */
	public void setOrderidentifier(String orderidentifier) {
		this.orderidentifier = orderidentifier == null ? null : orderidentifier
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_Order.OrderNo
	 * @return  the value of Inst_Order.OrderNo
	 * @mbggenerated
	 */
	public String getOrderno() {
		return orderno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_Order.OrderNo
	 * @param orderno  the value for Inst_Order.OrderNo
	 * @mbggenerated
	 */
	public void setOrderno(String orderno) {
		this.orderno = orderno == null ? null : orderno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_Order.OrderSubNo
	 * @return  the value of Inst_Order.OrderSubNo
	 * @mbggenerated
	 */
	public String getOrdersubno() {
		return ordersubno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_Order.OrderSubNo
	 * @param ordersubno  the value for Inst_Order.OrderSubNo
	 * @mbggenerated
	 */
	public void setOrdersubno(String ordersubno) {
		this.ordersubno = ordersubno == null ? null : ordersubno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_Order.PatientIdentifier_Id
	 * @return  the value of Inst_Order.PatientIdentifier_Id
	 * @mbggenerated
	 */
	public String getPatientidentifierId() {
		return patientidentifierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_Order.PatientIdentifier_Id
	 * @param patientidentifierId  the value for Inst_Order.PatientIdentifier_Id
	 * @mbggenerated
	 */
	public void setPatientidentifierId(String patientidentifierId) {
		this.patientidentifierId = patientidentifierId == null ? null
				: patientidentifierId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_Order.RepeatOrder
	 * @return  the value of Inst_Order.RepeatOrder
	 * @mbggenerated
	 */
	public Boolean getRepeatorder() {
		return repeatorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_Order.RepeatOrder
	 * @param repeatorder  the value for Inst_Order.RepeatOrder
	 * @mbggenerated
	 */
	public void setRepeatorder(Boolean repeatorder) {
		this.repeatorder = repeatorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_Order.ReservedOrder
	 * @return  the value of Inst_Order.ReservedOrder
	 * @mbggenerated
	 */
	public Boolean getReservedorder() {
		return reservedorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_Order.ReservedOrder
	 * @param reservedorder  the value for Inst_Order.ReservedOrder
	 * @mbggenerated
	 */
	public void setReservedorder(Boolean reservedorder) {
		this.reservedorder = reservedorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Inst_Order.SubsequentOrder
	 * @return  the value of Inst_Order.SubsequentOrder
	 * @mbggenerated
	 */
	public Boolean getSubsequentorder() {
		return subsequentorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Inst_Order.SubsequentOrder
	 * @param subsequentorder  the value for Inst_Order.SubsequentOrder
	 * @mbggenerated
	 */
	public void setSubsequentorder(Boolean subsequentorder) {
		this.subsequentorder = subsequentorder;
	}
}