package com.vico.clever.cdr.service.model;

import java.util.Date;

public class PatientInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.Guid
	 * @mbggenerated
	 */
	private String guid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_AboBloodType
	 * @mbggenerated
	 */
	private String demographicdetailsAbobloodtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_BiometricIdentifier_TypeOfBiometric_Code
	 * @mbggenerated
	 */
	private String demographicdetailsBiometricidentifierTypeofbiometricCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_BiometricIdentifier_TypeOfBiometric_Name
	 * @mbggenerated
	 */
	private String demographicdetailsBiometricidentifierTypeofbiometricName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_BirthData_BirthAddressDescription
	 * @mbggenerated
	 */
	private String demographicdetailsBirthdataBirthaddressdescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_BirthData_BirthDate
	 * @mbggenerated
	 */
	private Date demographicdetailsBirthdataBirthdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_BirthData_CityTownLocality_Code
	 * @mbggenerated
	 */
	private String demographicdetailsBirthdataCitytownlocalityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_BirthData_CityTownLocality_Name
	 * @mbggenerated
	 */
	private String demographicdetailsBirthdataCitytownlocalityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_BirthData_CountryOfBirth_Code
	 * @mbggenerated
	 */
	private String demographicdetailsBirthdataCountryofbirthCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_BirthData_CountryOfBirth_Name
	 * @mbggenerated
	 */
	private String demographicdetailsBirthdataCountryofbirthName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_BirthData_Registry
	 * @mbggenerated
	 */
	private String demographicdetailsBirthdataRegistry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_BirthData_StateTerritoryProvince_Code
	 * @mbggenerated
	 */
	private String demographicdetailsBirthdataStateterritoryprovinceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_BirthData_StateTerritoryProvince_Name
	 * @mbggenerated
	 */
	private String demographicdetailsBirthdataStateterritoryprovinceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_DeathData_CityTownLocality_Code
	 * @mbggenerated
	 */
	private String demographicdetailsDeathdataCitytownlocalityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_DeathData_CityTownLocality_Name
	 * @mbggenerated
	 */
	private String demographicdetailsDeathdataCitytownlocalityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_DeathData_Country_Code
	 * @mbggenerated
	 */
	private String demographicdetailsDeathdataCountryCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_DeathData_Country_Name
	 * @mbggenerated
	 */
	private String demographicdetailsDeathdataCountryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_DeathData_DeathDate
	 * @mbggenerated
	 */
	private Date demographicdetailsDeathdataDeathdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_DeathData_StateTerritoryProvince_Code
	 * @mbggenerated
	 */
	private String demographicdetailsDeathdataStateterritoryprovinceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_DeathData_StateTerritoryProvince_Name
	 * @mbggenerated
	 */
	private String demographicdetailsDeathdataStateterritoryprovinceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_EducationBackground
	 * @mbggenerated
	 */
	private String demographicdetailsEducationbackground;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_EthnicBackground_Code
	 * @mbggenerated
	 */
	private String demographicdetailsEthnicbackgroundCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_EthnicBackground_Name
	 * @mbggenerated
	 */
	private String demographicdetailsEthnicbackgroundName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_Gender_Code
	 * @mbggenerated
	 */
	private String demographicdetailsGenderCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_Gender_Name
	 * @mbggenerated
	 */
	private String demographicdetailsGenderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_MaritalStatus_Code
	 * @mbggenerated
	 */
	private String demographicdetailsMaritalstatusCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_MaritalStatus_Name
	 * @mbggenerated
	 */
	private String demographicdetailsMaritalstatusName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_Nationlity
	 * @mbggenerated
	 */
	private String demographicdetailsNationlity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_Profession
	 * @mbggenerated
	 */
	private String demographicdetailsProfession;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.DemographicDetails_RhBloodType
	 * @mbggenerated
	 */
	private String demographicdetailsRhbloodtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.HealthcareIdentifier_GeographicScope_Code
	 * @mbggenerated
	 */
	private String healthcareidentifierGeographicscopeCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.HealthcareIdentifier_GeographicScope_Name
	 * @mbggenerated
	 */
	private String healthcareidentifierGeographicscopeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.HealthcareIdentifier_IdentifierMainData_Id
	 * @mbggenerated
	 */
	private String healthcareidentifierIdentifiermaindataId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.IdNumber_GeographicScope_Code
	 * @mbggenerated
	 */
	private String idnumberGeographicscopeCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.IdNumber_GeographicScope_Name
	 * @mbggenerated
	 */
	private String idnumberGeographicscopeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.IdNumber_IdentifierMainData_Id
	 * @mbggenerated
	 */
	private String idnumberIdentifiermaindataId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.Name_Code
	 * @mbggenerated
	 */
	private String nameCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.Name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.Name_Name_FullName
	 * @mbggenerated
	 */
	private String nameNameFullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.Name_Name_PreferredName
	 * @mbggenerated
	 */
	private Boolean nameNamePreferredname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.PatientIdentifier_GeographicScope_Code
	 * @mbggenerated
	 */
	private String patientidentifierGeographicscopeCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.PatientIdentifier_GeographicScope_Name
	 * @mbggenerated
	 */
	private String patientidentifierGeographicscopeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.PatientIdentifier_IdentifierMainData_Id
	 * @mbggenerated
	 */
	private String patientidentifierIdentifiermaindataId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.Relationships_PersonalRelationship_RelationshipType_Code
	 * @mbggenerated
	 */
	private String relationshipsPersonalrelationshipRelationshiptypeCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Person_Patient.Relationships_PersonalRelationship_RelationshipType_Name
	 * @mbggenerated
	 */
	private String relationshipsPersonalrelationshipRelationshiptypeName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.Guid
	 * @return  the value of Person_Patient.Guid
	 * @mbggenerated
	 */
	public String getGuid() {
		return guid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.Guid
	 * @param guid  the value for Person_Patient.Guid
	 * @mbggenerated
	 */
	public void setGuid(String guid) {
		this.guid = guid == null ? null : guid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_AboBloodType
	 * @return  the value of Person_Patient.DemographicDetails_AboBloodType
	 * @mbggenerated
	 */
	public String getDemographicdetailsAbobloodtype() {
		return demographicdetailsAbobloodtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_AboBloodType
	 * @param demographicdetailsAbobloodtype  the value for Person_Patient.DemographicDetails_AboBloodType
	 * @mbggenerated
	 */
	public void setDemographicdetailsAbobloodtype(
			String demographicdetailsAbobloodtype) {
		this.demographicdetailsAbobloodtype = demographicdetailsAbobloodtype == null ? null
				: demographicdetailsAbobloodtype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_BiometricIdentifier_TypeOfBiometric_Code
	 * @return  the value of Person_Patient.DemographicDetails_BiometricIdentifier_TypeOfBiometric_Code
	 * @mbggenerated
	 */
	public String getDemographicdetailsBiometricidentifierTypeofbiometricCode() {
		return demographicdetailsBiometricidentifierTypeofbiometricCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_BiometricIdentifier_TypeOfBiometric_Code
	 * @param demographicdetailsBiometricidentifierTypeofbiometricCode  the value for Person_Patient.DemographicDetails_BiometricIdentifier_TypeOfBiometric_Code
	 * @mbggenerated
	 */
	public void setDemographicdetailsBiometricidentifierTypeofbiometricCode(
			String demographicdetailsBiometricidentifierTypeofbiometricCode) {
		this.demographicdetailsBiometricidentifierTypeofbiometricCode = demographicdetailsBiometricidentifierTypeofbiometricCode == null ? null
				: demographicdetailsBiometricidentifierTypeofbiometricCode
						.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_BiometricIdentifier_TypeOfBiometric_Name
	 * @return  the value of Person_Patient.DemographicDetails_BiometricIdentifier_TypeOfBiometric_Name
	 * @mbggenerated
	 */
	public String getDemographicdetailsBiometricidentifierTypeofbiometricName() {
		return demographicdetailsBiometricidentifierTypeofbiometricName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_BiometricIdentifier_TypeOfBiometric_Name
	 * @param demographicdetailsBiometricidentifierTypeofbiometricName  the value for Person_Patient.DemographicDetails_BiometricIdentifier_TypeOfBiometric_Name
	 * @mbggenerated
	 */
	public void setDemographicdetailsBiometricidentifierTypeofbiometricName(
			String demographicdetailsBiometricidentifierTypeofbiometricName) {
		this.demographicdetailsBiometricidentifierTypeofbiometricName = demographicdetailsBiometricidentifierTypeofbiometricName == null ? null
				: demographicdetailsBiometricidentifierTypeofbiometricName
						.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_BirthData_BirthAddressDescription
	 * @return  the value of Person_Patient.DemographicDetails_BirthData_BirthAddressDescription
	 * @mbggenerated
	 */
	public String getDemographicdetailsBirthdataBirthaddressdescription() {
		return demographicdetailsBirthdataBirthaddressdescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_BirthData_BirthAddressDescription
	 * @param demographicdetailsBirthdataBirthaddressdescription  the value for Person_Patient.DemographicDetails_BirthData_BirthAddressDescription
	 * @mbggenerated
	 */
	public void setDemographicdetailsBirthdataBirthaddressdescription(
			String demographicdetailsBirthdataBirthaddressdescription) {
		this.demographicdetailsBirthdataBirthaddressdescription = demographicdetailsBirthdataBirthaddressdescription == null ? null
				: demographicdetailsBirthdataBirthaddressdescription.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_BirthData_BirthDate
	 * @return  the value of Person_Patient.DemographicDetails_BirthData_BirthDate
	 * @mbggenerated
	 */
	public Date getDemographicdetailsBirthdataBirthdate() {
		return demographicdetailsBirthdataBirthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_BirthData_BirthDate
	 * @param demographicdetailsBirthdataBirthdate  the value for Person_Patient.DemographicDetails_BirthData_BirthDate
	 * @mbggenerated
	 */
	public void setDemographicdetailsBirthdataBirthdate(
			Date demographicdetailsBirthdataBirthdate) {
		this.demographicdetailsBirthdataBirthdate = demographicdetailsBirthdataBirthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_BirthData_CityTownLocality_Code
	 * @return  the value of Person_Patient.DemographicDetails_BirthData_CityTownLocality_Code
	 * @mbggenerated
	 */
	public String getDemographicdetailsBirthdataCitytownlocalityCode() {
		return demographicdetailsBirthdataCitytownlocalityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_BirthData_CityTownLocality_Code
	 * @param demographicdetailsBirthdataCitytownlocalityCode  the value for Person_Patient.DemographicDetails_BirthData_CityTownLocality_Code
	 * @mbggenerated
	 */
	public void setDemographicdetailsBirthdataCitytownlocalityCode(
			String demographicdetailsBirthdataCitytownlocalityCode) {
		this.demographicdetailsBirthdataCitytownlocalityCode = demographicdetailsBirthdataCitytownlocalityCode == null ? null
				: demographicdetailsBirthdataCitytownlocalityCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_BirthData_CityTownLocality_Name
	 * @return  the value of Person_Patient.DemographicDetails_BirthData_CityTownLocality_Name
	 * @mbggenerated
	 */
	public String getDemographicdetailsBirthdataCitytownlocalityName() {
		return demographicdetailsBirthdataCitytownlocalityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_BirthData_CityTownLocality_Name
	 * @param demographicdetailsBirthdataCitytownlocalityName  the value for Person_Patient.DemographicDetails_BirthData_CityTownLocality_Name
	 * @mbggenerated
	 */
	public void setDemographicdetailsBirthdataCitytownlocalityName(
			String demographicdetailsBirthdataCitytownlocalityName) {
		this.demographicdetailsBirthdataCitytownlocalityName = demographicdetailsBirthdataCitytownlocalityName == null ? null
				: demographicdetailsBirthdataCitytownlocalityName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_BirthData_CountryOfBirth_Code
	 * @return  the value of Person_Patient.DemographicDetails_BirthData_CountryOfBirth_Code
	 * @mbggenerated
	 */
	public String getDemographicdetailsBirthdataCountryofbirthCode() {
		return demographicdetailsBirthdataCountryofbirthCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_BirthData_CountryOfBirth_Code
	 * @param demographicdetailsBirthdataCountryofbirthCode  the value for Person_Patient.DemographicDetails_BirthData_CountryOfBirth_Code
	 * @mbggenerated
	 */
	public void setDemographicdetailsBirthdataCountryofbirthCode(
			String demographicdetailsBirthdataCountryofbirthCode) {
		this.demographicdetailsBirthdataCountryofbirthCode = demographicdetailsBirthdataCountryofbirthCode == null ? null
				: demographicdetailsBirthdataCountryofbirthCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_BirthData_CountryOfBirth_Name
	 * @return  the value of Person_Patient.DemographicDetails_BirthData_CountryOfBirth_Name
	 * @mbggenerated
	 */
	public String getDemographicdetailsBirthdataCountryofbirthName() {
		return demographicdetailsBirthdataCountryofbirthName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_BirthData_CountryOfBirth_Name
	 * @param demographicdetailsBirthdataCountryofbirthName  the value for Person_Patient.DemographicDetails_BirthData_CountryOfBirth_Name
	 * @mbggenerated
	 */
	public void setDemographicdetailsBirthdataCountryofbirthName(
			String demographicdetailsBirthdataCountryofbirthName) {
		this.demographicdetailsBirthdataCountryofbirthName = demographicdetailsBirthdataCountryofbirthName == null ? null
				: demographicdetailsBirthdataCountryofbirthName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_BirthData_Registry
	 * @return  the value of Person_Patient.DemographicDetails_BirthData_Registry
	 * @mbggenerated
	 */
	public String getDemographicdetailsBirthdataRegistry() {
		return demographicdetailsBirthdataRegistry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_BirthData_Registry
	 * @param demographicdetailsBirthdataRegistry  the value for Person_Patient.DemographicDetails_BirthData_Registry
	 * @mbggenerated
	 */
	public void setDemographicdetailsBirthdataRegistry(
			String demographicdetailsBirthdataRegistry) {
		this.demographicdetailsBirthdataRegistry = demographicdetailsBirthdataRegistry == null ? null
				: demographicdetailsBirthdataRegistry.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_BirthData_StateTerritoryProvince_Code
	 * @return  the value of Person_Patient.DemographicDetails_BirthData_StateTerritoryProvince_Code
	 * @mbggenerated
	 */
	public String getDemographicdetailsBirthdataStateterritoryprovinceCode() {
		return demographicdetailsBirthdataStateterritoryprovinceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_BirthData_StateTerritoryProvince_Code
	 * @param demographicdetailsBirthdataStateterritoryprovinceCode  the value for Person_Patient.DemographicDetails_BirthData_StateTerritoryProvince_Code
	 * @mbggenerated
	 */
	public void setDemographicdetailsBirthdataStateterritoryprovinceCode(
			String demographicdetailsBirthdataStateterritoryprovinceCode) {
		this.demographicdetailsBirthdataStateterritoryprovinceCode = demographicdetailsBirthdataStateterritoryprovinceCode == null ? null
				: demographicdetailsBirthdataStateterritoryprovinceCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_BirthData_StateTerritoryProvince_Name
	 * @return  the value of Person_Patient.DemographicDetails_BirthData_StateTerritoryProvince_Name
	 * @mbggenerated
	 */
	public String getDemographicdetailsBirthdataStateterritoryprovinceName() {
		return demographicdetailsBirthdataStateterritoryprovinceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_BirthData_StateTerritoryProvince_Name
	 * @param demographicdetailsBirthdataStateterritoryprovinceName  the value for Person_Patient.DemographicDetails_BirthData_StateTerritoryProvince_Name
	 * @mbggenerated
	 */
	public void setDemographicdetailsBirthdataStateterritoryprovinceName(
			String demographicdetailsBirthdataStateterritoryprovinceName) {
		this.demographicdetailsBirthdataStateterritoryprovinceName = demographicdetailsBirthdataStateterritoryprovinceName == null ? null
				: demographicdetailsBirthdataStateterritoryprovinceName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_DeathData_CityTownLocality_Code
	 * @return  the value of Person_Patient.DemographicDetails_DeathData_CityTownLocality_Code
	 * @mbggenerated
	 */
	public String getDemographicdetailsDeathdataCitytownlocalityCode() {
		return demographicdetailsDeathdataCitytownlocalityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_DeathData_CityTownLocality_Code
	 * @param demographicdetailsDeathdataCitytownlocalityCode  the value for Person_Patient.DemographicDetails_DeathData_CityTownLocality_Code
	 * @mbggenerated
	 */
	public void setDemographicdetailsDeathdataCitytownlocalityCode(
			String demographicdetailsDeathdataCitytownlocalityCode) {
		this.demographicdetailsDeathdataCitytownlocalityCode = demographicdetailsDeathdataCitytownlocalityCode == null ? null
				: demographicdetailsDeathdataCitytownlocalityCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_DeathData_CityTownLocality_Name
	 * @return  the value of Person_Patient.DemographicDetails_DeathData_CityTownLocality_Name
	 * @mbggenerated
	 */
	public String getDemographicdetailsDeathdataCitytownlocalityName() {
		return demographicdetailsDeathdataCitytownlocalityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_DeathData_CityTownLocality_Name
	 * @param demographicdetailsDeathdataCitytownlocalityName  the value for Person_Patient.DemographicDetails_DeathData_CityTownLocality_Name
	 * @mbggenerated
	 */
	public void setDemographicdetailsDeathdataCitytownlocalityName(
			String demographicdetailsDeathdataCitytownlocalityName) {
		this.demographicdetailsDeathdataCitytownlocalityName = demographicdetailsDeathdataCitytownlocalityName == null ? null
				: demographicdetailsDeathdataCitytownlocalityName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_DeathData_Country_Code
	 * @return  the value of Person_Patient.DemographicDetails_DeathData_Country_Code
	 * @mbggenerated
	 */
	public String getDemographicdetailsDeathdataCountryCode() {
		return demographicdetailsDeathdataCountryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_DeathData_Country_Code
	 * @param demographicdetailsDeathdataCountryCode  the value for Person_Patient.DemographicDetails_DeathData_Country_Code
	 * @mbggenerated
	 */
	public void setDemographicdetailsDeathdataCountryCode(
			String demographicdetailsDeathdataCountryCode) {
		this.demographicdetailsDeathdataCountryCode = demographicdetailsDeathdataCountryCode == null ? null
				: demographicdetailsDeathdataCountryCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_DeathData_Country_Name
	 * @return  the value of Person_Patient.DemographicDetails_DeathData_Country_Name
	 * @mbggenerated
	 */
	public String getDemographicdetailsDeathdataCountryName() {
		return demographicdetailsDeathdataCountryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_DeathData_Country_Name
	 * @param demographicdetailsDeathdataCountryName  the value for Person_Patient.DemographicDetails_DeathData_Country_Name
	 * @mbggenerated
	 */
	public void setDemographicdetailsDeathdataCountryName(
			String demographicdetailsDeathdataCountryName) {
		this.demographicdetailsDeathdataCountryName = demographicdetailsDeathdataCountryName == null ? null
				: demographicdetailsDeathdataCountryName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_DeathData_DeathDate
	 * @return  the value of Person_Patient.DemographicDetails_DeathData_DeathDate
	 * @mbggenerated
	 */
	public Date getDemographicdetailsDeathdataDeathdate() {
		return demographicdetailsDeathdataDeathdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_DeathData_DeathDate
	 * @param demographicdetailsDeathdataDeathdate  the value for Person_Patient.DemographicDetails_DeathData_DeathDate
	 * @mbggenerated
	 */
	public void setDemographicdetailsDeathdataDeathdate(
			Date demographicdetailsDeathdataDeathdate) {
		this.demographicdetailsDeathdataDeathdate = demographicdetailsDeathdataDeathdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_DeathData_StateTerritoryProvince_Code
	 * @return  the value of Person_Patient.DemographicDetails_DeathData_StateTerritoryProvince_Code
	 * @mbggenerated
	 */
	public String getDemographicdetailsDeathdataStateterritoryprovinceCode() {
		return demographicdetailsDeathdataStateterritoryprovinceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_DeathData_StateTerritoryProvince_Code
	 * @param demographicdetailsDeathdataStateterritoryprovinceCode  the value for Person_Patient.DemographicDetails_DeathData_StateTerritoryProvince_Code
	 * @mbggenerated
	 */
	public void setDemographicdetailsDeathdataStateterritoryprovinceCode(
			String demographicdetailsDeathdataStateterritoryprovinceCode) {
		this.demographicdetailsDeathdataStateterritoryprovinceCode = demographicdetailsDeathdataStateterritoryprovinceCode == null ? null
				: demographicdetailsDeathdataStateterritoryprovinceCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_DeathData_StateTerritoryProvince_Name
	 * @return  the value of Person_Patient.DemographicDetails_DeathData_StateTerritoryProvince_Name
	 * @mbggenerated
	 */
	public String getDemographicdetailsDeathdataStateterritoryprovinceName() {
		return demographicdetailsDeathdataStateterritoryprovinceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_DeathData_StateTerritoryProvince_Name
	 * @param demographicdetailsDeathdataStateterritoryprovinceName  the value for Person_Patient.DemographicDetails_DeathData_StateTerritoryProvince_Name
	 * @mbggenerated
	 */
	public void setDemographicdetailsDeathdataStateterritoryprovinceName(
			String demographicdetailsDeathdataStateterritoryprovinceName) {
		this.demographicdetailsDeathdataStateterritoryprovinceName = demographicdetailsDeathdataStateterritoryprovinceName == null ? null
				: demographicdetailsDeathdataStateterritoryprovinceName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_EducationBackground
	 * @return  the value of Person_Patient.DemographicDetails_EducationBackground
	 * @mbggenerated
	 */
	public String getDemographicdetailsEducationbackground() {
		return demographicdetailsEducationbackground;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_EducationBackground
	 * @param demographicdetailsEducationbackground  the value for Person_Patient.DemographicDetails_EducationBackground
	 * @mbggenerated
	 */
	public void setDemographicdetailsEducationbackground(
			String demographicdetailsEducationbackground) {
		this.demographicdetailsEducationbackground = demographicdetailsEducationbackground == null ? null
				: demographicdetailsEducationbackground.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_EthnicBackground_Code
	 * @return  the value of Person_Patient.DemographicDetails_EthnicBackground_Code
	 * @mbggenerated
	 */
	public String getDemographicdetailsEthnicbackgroundCode() {
		return demographicdetailsEthnicbackgroundCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_EthnicBackground_Code
	 * @param demographicdetailsEthnicbackgroundCode  the value for Person_Patient.DemographicDetails_EthnicBackground_Code
	 * @mbggenerated
	 */
	public void setDemographicdetailsEthnicbackgroundCode(
			String demographicdetailsEthnicbackgroundCode) {
		this.demographicdetailsEthnicbackgroundCode = demographicdetailsEthnicbackgroundCode == null ? null
				: demographicdetailsEthnicbackgroundCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_EthnicBackground_Name
	 * @return  the value of Person_Patient.DemographicDetails_EthnicBackground_Name
	 * @mbggenerated
	 */
	public String getDemographicdetailsEthnicbackgroundName() {
		return demographicdetailsEthnicbackgroundName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_EthnicBackground_Name
	 * @param demographicdetailsEthnicbackgroundName  the value for Person_Patient.DemographicDetails_EthnicBackground_Name
	 * @mbggenerated
	 */
	public void setDemographicdetailsEthnicbackgroundName(
			String demographicdetailsEthnicbackgroundName) {
		this.demographicdetailsEthnicbackgroundName = demographicdetailsEthnicbackgroundName == null ? null
				: demographicdetailsEthnicbackgroundName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_Gender_Code
	 * @return  the value of Person_Patient.DemographicDetails_Gender_Code
	 * @mbggenerated
	 */
	public String getDemographicdetailsGenderCode() {
		return demographicdetailsGenderCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_Gender_Code
	 * @param demographicdetailsGenderCode  the value for Person_Patient.DemographicDetails_Gender_Code
	 * @mbggenerated
	 */
	public void setDemographicdetailsGenderCode(
			String demographicdetailsGenderCode) {
		this.demographicdetailsGenderCode = demographicdetailsGenderCode == null ? null
				: demographicdetailsGenderCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_Gender_Name
	 * @return  the value of Person_Patient.DemographicDetails_Gender_Name
	 * @mbggenerated
	 */
	public String getDemographicdetailsGenderName() {
		return demographicdetailsGenderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_Gender_Name
	 * @param demographicdetailsGenderName  the value for Person_Patient.DemographicDetails_Gender_Name
	 * @mbggenerated
	 */
	public void setDemographicdetailsGenderName(
			String demographicdetailsGenderName) {
		this.demographicdetailsGenderName = demographicdetailsGenderName == null ? null
				: demographicdetailsGenderName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_MaritalStatus_Code
	 * @return  the value of Person_Patient.DemographicDetails_MaritalStatus_Code
	 * @mbggenerated
	 */
	public String getDemographicdetailsMaritalstatusCode() {
		return demographicdetailsMaritalstatusCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_MaritalStatus_Code
	 * @param demographicdetailsMaritalstatusCode  the value for Person_Patient.DemographicDetails_MaritalStatus_Code
	 * @mbggenerated
	 */
	public void setDemographicdetailsMaritalstatusCode(
			String demographicdetailsMaritalstatusCode) {
		this.demographicdetailsMaritalstatusCode = demographicdetailsMaritalstatusCode == null ? null
				: demographicdetailsMaritalstatusCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_MaritalStatus_Name
	 * @return  the value of Person_Patient.DemographicDetails_MaritalStatus_Name
	 * @mbggenerated
	 */
	public String getDemographicdetailsMaritalstatusName() {
		return demographicdetailsMaritalstatusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_MaritalStatus_Name
	 * @param demographicdetailsMaritalstatusName  the value for Person_Patient.DemographicDetails_MaritalStatus_Name
	 * @mbggenerated
	 */
	public void setDemographicdetailsMaritalstatusName(
			String demographicdetailsMaritalstatusName) {
		this.demographicdetailsMaritalstatusName = demographicdetailsMaritalstatusName == null ? null
				: demographicdetailsMaritalstatusName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_Nationlity
	 * @return  the value of Person_Patient.DemographicDetails_Nationlity
	 * @mbggenerated
	 */
	public String getDemographicdetailsNationlity() {
		return demographicdetailsNationlity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_Nationlity
	 * @param demographicdetailsNationlity  the value for Person_Patient.DemographicDetails_Nationlity
	 * @mbggenerated
	 */
	public void setDemographicdetailsNationlity(
			String demographicdetailsNationlity) {
		this.demographicdetailsNationlity = demographicdetailsNationlity == null ? null
				: demographicdetailsNationlity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_Profession
	 * @return  the value of Person_Patient.DemographicDetails_Profession
	 * @mbggenerated
	 */
	public String getDemographicdetailsProfession() {
		return demographicdetailsProfession;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_Profession
	 * @param demographicdetailsProfession  the value for Person_Patient.DemographicDetails_Profession
	 * @mbggenerated
	 */
	public void setDemographicdetailsProfession(
			String demographicdetailsProfession) {
		this.demographicdetailsProfession = demographicdetailsProfession == null ? null
				: demographicdetailsProfession.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.DemographicDetails_RhBloodType
	 * @return  the value of Person_Patient.DemographicDetails_RhBloodType
	 * @mbggenerated
	 */
	public String getDemographicdetailsRhbloodtype() {
		return demographicdetailsRhbloodtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.DemographicDetails_RhBloodType
	 * @param demographicdetailsRhbloodtype  the value for Person_Patient.DemographicDetails_RhBloodType
	 * @mbggenerated
	 */
	public void setDemographicdetailsRhbloodtype(
			String demographicdetailsRhbloodtype) {
		this.demographicdetailsRhbloodtype = demographicdetailsRhbloodtype == null ? null
				: demographicdetailsRhbloodtype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.HealthcareIdentifier_GeographicScope_Code
	 * @return  the value of Person_Patient.HealthcareIdentifier_GeographicScope_Code
	 * @mbggenerated
	 */
	public String getHealthcareidentifierGeographicscopeCode() {
		return healthcareidentifierGeographicscopeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.HealthcareIdentifier_GeographicScope_Code
	 * @param healthcareidentifierGeographicscopeCode  the value for Person_Patient.HealthcareIdentifier_GeographicScope_Code
	 * @mbggenerated
	 */
	public void setHealthcareidentifierGeographicscopeCode(
			String healthcareidentifierGeographicscopeCode) {
		this.healthcareidentifierGeographicscopeCode = healthcareidentifierGeographicscopeCode == null ? null
				: healthcareidentifierGeographicscopeCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.HealthcareIdentifier_GeographicScope_Name
	 * @return  the value of Person_Patient.HealthcareIdentifier_GeographicScope_Name
	 * @mbggenerated
	 */
	public String getHealthcareidentifierGeographicscopeName() {
		return healthcareidentifierGeographicscopeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.HealthcareIdentifier_GeographicScope_Name
	 * @param healthcareidentifierGeographicscopeName  the value for Person_Patient.HealthcareIdentifier_GeographicScope_Name
	 * @mbggenerated
	 */
	public void setHealthcareidentifierGeographicscopeName(
			String healthcareidentifierGeographicscopeName) {
		this.healthcareidentifierGeographicscopeName = healthcareidentifierGeographicscopeName == null ? null
				: healthcareidentifierGeographicscopeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.HealthcareIdentifier_IdentifierMainData_Id
	 * @return  the value of Person_Patient.HealthcareIdentifier_IdentifierMainData_Id
	 * @mbggenerated
	 */
	public String getHealthcareidentifierIdentifiermaindataId() {
		return healthcareidentifierIdentifiermaindataId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.HealthcareIdentifier_IdentifierMainData_Id
	 * @param healthcareidentifierIdentifiermaindataId  the value for Person_Patient.HealthcareIdentifier_IdentifierMainData_Id
	 * @mbggenerated
	 */
	public void setHealthcareidentifierIdentifiermaindataId(
			String healthcareidentifierIdentifiermaindataId) {
		this.healthcareidentifierIdentifiermaindataId = healthcareidentifierIdentifiermaindataId == null ? null
				: healthcareidentifierIdentifiermaindataId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.IdNumber_GeographicScope_Code
	 * @return  the value of Person_Patient.IdNumber_GeographicScope_Code
	 * @mbggenerated
	 */
	public String getIdnumberGeographicscopeCode() {
		return idnumberGeographicscopeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.IdNumber_GeographicScope_Code
	 * @param idnumberGeographicscopeCode  the value for Person_Patient.IdNumber_GeographicScope_Code
	 * @mbggenerated
	 */
	public void setIdnumberGeographicscopeCode(
			String idnumberGeographicscopeCode) {
		this.idnumberGeographicscopeCode = idnumberGeographicscopeCode == null ? null
				: idnumberGeographicscopeCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.IdNumber_GeographicScope_Name
	 * @return  the value of Person_Patient.IdNumber_GeographicScope_Name
	 * @mbggenerated
	 */
	public String getIdnumberGeographicscopeName() {
		return idnumberGeographicscopeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.IdNumber_GeographicScope_Name
	 * @param idnumberGeographicscopeName  the value for Person_Patient.IdNumber_GeographicScope_Name
	 * @mbggenerated
	 */
	public void setIdnumberGeographicscopeName(
			String idnumberGeographicscopeName) {
		this.idnumberGeographicscopeName = idnumberGeographicscopeName == null ? null
				: idnumberGeographicscopeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.IdNumber_IdentifierMainData_Id
	 * @return  the value of Person_Patient.IdNumber_IdentifierMainData_Id
	 * @mbggenerated
	 */
	public String getIdnumberIdentifiermaindataId() {
		return idnumberIdentifiermaindataId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.IdNumber_IdentifierMainData_Id
	 * @param idnumberIdentifiermaindataId  the value for Person_Patient.IdNumber_IdentifierMainData_Id
	 * @mbggenerated
	 */
	public void setIdnumberIdentifiermaindataId(
			String idnumberIdentifiermaindataId) {
		this.idnumberIdentifiermaindataId = idnumberIdentifiermaindataId == null ? null
				: idnumberIdentifiermaindataId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.Name_Code
	 * @return  the value of Person_Patient.Name_Code
	 * @mbggenerated
	 */
	public String getNameCode() {
		return nameCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.Name_Code
	 * @param nameCode  the value for Person_Patient.Name_Code
	 * @mbggenerated
	 */
	public void setNameCode(String nameCode) {
		this.nameCode = nameCode == null ? null : nameCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.Name
	 * @return  the value of Person_Patient.Name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.Name
	 * @param name  the value for Person_Patient.Name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.Name_Name_FullName
	 * @return  the value of Person_Patient.Name_Name_FullName
	 * @mbggenerated
	 */
	public String getNameNameFullname() {
		return nameNameFullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.Name_Name_FullName
	 * @param nameNameFullname  the value for Person_Patient.Name_Name_FullName
	 * @mbggenerated
	 */
	public void setNameNameFullname(String nameNameFullname) {
		this.nameNameFullname = nameNameFullname == null ? null
				: nameNameFullname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.Name_Name_PreferredName
	 * @return  the value of Person_Patient.Name_Name_PreferredName
	 * @mbggenerated
	 */
	public Boolean getNameNamePreferredname() {
		return nameNamePreferredname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.Name_Name_PreferredName
	 * @param nameNamePreferredname  the value for Person_Patient.Name_Name_PreferredName
	 * @mbggenerated
	 */
	public void setNameNamePreferredname(Boolean nameNamePreferredname) {
		this.nameNamePreferredname = nameNamePreferredname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.PatientIdentifier_GeographicScope_Code
	 * @return  the value of Person_Patient.PatientIdentifier_GeographicScope_Code
	 * @mbggenerated
	 */
	public String getPatientidentifierGeographicscopeCode() {
		return patientidentifierGeographicscopeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.PatientIdentifier_GeographicScope_Code
	 * @param patientidentifierGeographicscopeCode  the value for Person_Patient.PatientIdentifier_GeographicScope_Code
	 * @mbggenerated
	 */
	public void setPatientidentifierGeographicscopeCode(
			String patientidentifierGeographicscopeCode) {
		this.patientidentifierGeographicscopeCode = patientidentifierGeographicscopeCode == null ? null
				: patientidentifierGeographicscopeCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.PatientIdentifier_GeographicScope_Name
	 * @return  the value of Person_Patient.PatientIdentifier_GeographicScope_Name
	 * @mbggenerated
	 */
	public String getPatientidentifierGeographicscopeName() {
		return patientidentifierGeographicscopeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.PatientIdentifier_GeographicScope_Name
	 * @param patientidentifierGeographicscopeName  the value for Person_Patient.PatientIdentifier_GeographicScope_Name
	 * @mbggenerated
	 */
	public void setPatientidentifierGeographicscopeName(
			String patientidentifierGeographicscopeName) {
		this.patientidentifierGeographicscopeName = patientidentifierGeographicscopeName == null ? null
				: patientidentifierGeographicscopeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.PatientIdentifier_IdentifierMainData_Id
	 * @return  the value of Person_Patient.PatientIdentifier_IdentifierMainData_Id
	 * @mbggenerated
	 */
	public String getPatientidentifierIdentifiermaindataId() {
		return patientidentifierIdentifiermaindataId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.PatientIdentifier_IdentifierMainData_Id
	 * @param patientidentifierIdentifiermaindataId  the value for Person_Patient.PatientIdentifier_IdentifierMainData_Id
	 * @mbggenerated
	 */
	public void setPatientidentifierIdentifiermaindataId(
			String patientidentifierIdentifiermaindataId) {
		this.patientidentifierIdentifiermaindataId = patientidentifierIdentifiermaindataId == null ? null
				: patientidentifierIdentifiermaindataId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.Relationships_PersonalRelationship_RelationshipType_Code
	 * @return  the value of Person_Patient.Relationships_PersonalRelationship_RelationshipType_Code
	 * @mbggenerated
	 */
	public String getRelationshipsPersonalrelationshipRelationshiptypeCode() {
		return relationshipsPersonalrelationshipRelationshiptypeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.Relationships_PersonalRelationship_RelationshipType_Code
	 * @param relationshipsPersonalrelationshipRelationshiptypeCode  the value for Person_Patient.Relationships_PersonalRelationship_RelationshipType_Code
	 * @mbggenerated
	 */
	public void setRelationshipsPersonalrelationshipRelationshiptypeCode(
			String relationshipsPersonalrelationshipRelationshiptypeCode) {
		this.relationshipsPersonalrelationshipRelationshiptypeCode = relationshipsPersonalrelationshipRelationshiptypeCode == null ? null
				: relationshipsPersonalrelationshipRelationshiptypeCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Person_Patient.Relationships_PersonalRelationship_RelationshipType_Name
	 * @return  the value of Person_Patient.Relationships_PersonalRelationship_RelationshipType_Name
	 * @mbggenerated
	 */
	public String getRelationshipsPersonalrelationshipRelationshiptypeName() {
		return relationshipsPersonalrelationshipRelationshiptypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Person_Patient.Relationships_PersonalRelationship_RelationshipType_Name
	 * @param relationshipsPersonalrelationshipRelationshiptypeName  the value for Person_Patient.Relationships_PersonalRelationship_RelationshipType_Name
	 * @mbggenerated
	 */
	public void setRelationshipsPersonalrelationshipRelationshiptypeName(
			String relationshipsPersonalrelationshipRelationshiptypeName) {
		this.relationshipsPersonalrelationshipRelationshiptypeName = relationshipsPersonalrelationshipRelationshiptypeName == null ? null
				: relationshipsPersonalrelationshipRelationshiptypeName.trim();
	}
}