package com.vico.clever.cdr.service.model;

import java.util.Date;

public class ProblemDiagnosis {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.Guid
	 * @mbggenerated
	 */
	private String guid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.ClassOfDiagnosis_Code
	 * @mbggenerated
	 */
	private String classofdiagnosisCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.ClassOfDiagnosis_Name
	 * @mbggenerated
	 */
	private String classofdiagnosisName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.Condition
	 * @mbggenerated
	 */
	private String condition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.DateOfDiagnosis
	 * @mbggenerated
	 */
	private Date dateofdiagnosis;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.DaysOfTreatment
	 * @mbggenerated
	 */
	private Integer daysoftreatment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.Description
	 * @mbggenerated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.DiagnosisIdentifier_Id
	 * @mbggenerated
	 */
	private String diagnosisidentifierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.Doctor
	 * @mbggenerated
	 */
	private String doctor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.EncounterIdentifier
	 * @mbggenerated
	 */
	private String encounteridentifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.FlagOfOperation
	 * @mbggenerated
	 */
	private String flagofoperation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.PatientIdentifier_Id
	 * @mbggenerated
	 */
	private String patientidentifierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.ProblemDiagnosis
	 * @mbggenerated
	 */
	private String problemdiagnosis;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.ResultOfTreatment
	 * @mbggenerated
	 */
	private String resultoftreatment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Eval_ProblemDiagnosis.SequenceNumberOfDiagnosis
	 * @mbggenerated
	 */
	private String sequencenumberofdiagnosis;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.Guid
	 * @return  the value of Eval_ProblemDiagnosis.Guid
	 * @mbggenerated
	 */
	public String getGuid() {
		return guid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.Guid
	 * @param guid  the value for Eval_ProblemDiagnosis.Guid
	 * @mbggenerated
	 */
	public void setGuid(String guid) {
		this.guid = guid == null ? null : guid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.ClassOfDiagnosis_Code
	 * @return  the value of Eval_ProblemDiagnosis.ClassOfDiagnosis_Code
	 * @mbggenerated
	 */
	public String getClassofdiagnosisCode() {
		return classofdiagnosisCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.ClassOfDiagnosis_Code
	 * @param classofdiagnosisCode  the value for Eval_ProblemDiagnosis.ClassOfDiagnosis_Code
	 * @mbggenerated
	 */
	public void setClassofdiagnosisCode(String classofdiagnosisCode) {
		this.classofdiagnosisCode = classofdiagnosisCode == null ? null
				: classofdiagnosisCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.ClassOfDiagnosis_Name
	 * @return  the value of Eval_ProblemDiagnosis.ClassOfDiagnosis_Name
	 * @mbggenerated
	 */
	public String getClassofdiagnosisName() {
		return classofdiagnosisName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.ClassOfDiagnosis_Name
	 * @param classofdiagnosisName  the value for Eval_ProblemDiagnosis.ClassOfDiagnosis_Name
	 * @mbggenerated
	 */
	public void setClassofdiagnosisName(String classofdiagnosisName) {
		this.classofdiagnosisName = classofdiagnosisName == null ? null
				: classofdiagnosisName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.Condition
	 * @return  the value of Eval_ProblemDiagnosis.Condition
	 * @mbggenerated
	 */
	public String getCondition() {
		return condition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.Condition
	 * @param condition  the value for Eval_ProblemDiagnosis.Condition
	 * @mbggenerated
	 */
	public void setCondition(String condition) {
		this.condition = condition == null ? null : condition.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.DateOfDiagnosis
	 * @return  the value of Eval_ProblemDiagnosis.DateOfDiagnosis
	 * @mbggenerated
	 */
	public Date getDateofdiagnosis() {
		return dateofdiagnosis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.DateOfDiagnosis
	 * @param dateofdiagnosis  the value for Eval_ProblemDiagnosis.DateOfDiagnosis
	 * @mbggenerated
	 */
	public void setDateofdiagnosis(Date dateofdiagnosis) {
		this.dateofdiagnosis = dateofdiagnosis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.DaysOfTreatment
	 * @return  the value of Eval_ProblemDiagnosis.DaysOfTreatment
	 * @mbggenerated
	 */
	public Integer getDaysoftreatment() {
		return daysoftreatment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.DaysOfTreatment
	 * @param daysoftreatment  the value for Eval_ProblemDiagnosis.DaysOfTreatment
	 * @mbggenerated
	 */
	public void setDaysoftreatment(Integer daysoftreatment) {
		this.daysoftreatment = daysoftreatment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.Description
	 * @return  the value of Eval_ProblemDiagnosis.Description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.Description
	 * @param description  the value for Eval_ProblemDiagnosis.Description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.DiagnosisIdentifier_Id
	 * @return  the value of Eval_ProblemDiagnosis.DiagnosisIdentifier_Id
	 * @mbggenerated
	 */
	public String getDiagnosisidentifierId() {
		return diagnosisidentifierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.DiagnosisIdentifier_Id
	 * @param diagnosisidentifierId  the value for Eval_ProblemDiagnosis.DiagnosisIdentifier_Id
	 * @mbggenerated
	 */
	public void setDiagnosisidentifierId(String diagnosisidentifierId) {
		this.diagnosisidentifierId = diagnosisidentifierId == null ? null
				: diagnosisidentifierId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.Doctor
	 * @return  the value of Eval_ProblemDiagnosis.Doctor
	 * @mbggenerated
	 */
	public String getDoctor() {
		return doctor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.Doctor
	 * @param doctor  the value for Eval_ProblemDiagnosis.Doctor
	 * @mbggenerated
	 */
	public void setDoctor(String doctor) {
		this.doctor = doctor == null ? null : doctor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.EncounterIdentifier
	 * @return  the value of Eval_ProblemDiagnosis.EncounterIdentifier
	 * @mbggenerated
	 */
	public String getEncounteridentifier() {
		return encounteridentifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.EncounterIdentifier
	 * @param encounteridentifier  the value for Eval_ProblemDiagnosis.EncounterIdentifier
	 * @mbggenerated
	 */
	public void setEncounteridentifier(String encounteridentifier) {
		this.encounteridentifier = encounteridentifier == null ? null
				: encounteridentifier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.FlagOfOperation
	 * @return  the value of Eval_ProblemDiagnosis.FlagOfOperation
	 * @mbggenerated
	 */
	public String getFlagofoperation() {
		return flagofoperation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.FlagOfOperation
	 * @param flagofoperation  the value for Eval_ProblemDiagnosis.FlagOfOperation
	 * @mbggenerated
	 */
	public void setFlagofoperation(String flagofoperation) {
		this.flagofoperation = flagofoperation == null ? null : flagofoperation
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.PatientIdentifier_Id
	 * @return  the value of Eval_ProblemDiagnosis.PatientIdentifier_Id
	 * @mbggenerated
	 */
	public String getPatientidentifierId() {
		return patientidentifierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.PatientIdentifier_Id
	 * @param patientidentifierId  the value for Eval_ProblemDiagnosis.PatientIdentifier_Id
	 * @mbggenerated
	 */
	public void setPatientidentifierId(String patientidentifierId) {
		this.patientidentifierId = patientidentifierId == null ? null
				: patientidentifierId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.ProblemDiagnosis
	 * @return  the value of Eval_ProblemDiagnosis.ProblemDiagnosis
	 * @mbggenerated
	 */
	public String getProblemdiagnosis() {
		return problemdiagnosis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.ProblemDiagnosis
	 * @param problemdiagnosis  the value for Eval_ProblemDiagnosis.ProblemDiagnosis
	 * @mbggenerated
	 */
	public void setProblemdiagnosis(String problemdiagnosis) {
		this.problemdiagnosis = problemdiagnosis == null ? null
				: problemdiagnosis.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.ResultOfTreatment
	 * @return  the value of Eval_ProblemDiagnosis.ResultOfTreatment
	 * @mbggenerated
	 */
	public String getResultoftreatment() {
		return resultoftreatment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.ResultOfTreatment
	 * @param resultoftreatment  the value for Eval_ProblemDiagnosis.ResultOfTreatment
	 * @mbggenerated
	 */
	public void setResultoftreatment(String resultoftreatment) {
		this.resultoftreatment = resultoftreatment == null ? null
				: resultoftreatment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Eval_ProblemDiagnosis.SequenceNumberOfDiagnosis
	 * @return  the value of Eval_ProblemDiagnosis.SequenceNumberOfDiagnosis
	 * @mbggenerated
	 */
	public String getSequencenumberofdiagnosis() {
		return sequencenumberofdiagnosis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Eval_ProblemDiagnosis.SequenceNumberOfDiagnosis
	 * @param sequencenumberofdiagnosis  the value for Eval_ProblemDiagnosis.SequenceNumberOfDiagnosis
	 * @mbggenerated
	 */
	public void setSequencenumberofdiagnosis(String sequencenumberofdiagnosis) {
		this.sequencenumberofdiagnosis = sequencenumberofdiagnosis == null ? null
				: sequencenumberofdiagnosis.trim();
	}
}