package com.test.mybatis.model;

import java.util.Date;

public class DrugDispenseReqStatus {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.Guid
	 * @mbggenerated
	 */
	private String guid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.DrugsDispensingRequestIdentifier
	 * @mbggenerated
	 */
	private String drugsdispensingrequestidentifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.EncounterIdentifier
	 * @mbggenerated
	 */
	private String encounteridentifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.IsmTransition_CareflowStep_Code
	 * @mbggenerated
	 */
	private String ismtransitionCareflowstepCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.IsmTransition_CareflowStep_Name
	 * @mbggenerated
	 */
	private String ismtransitionCareflowstepName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.IsmTransition_CurrentState_Code
	 * @mbggenerated
	 */
	private String ismtransitionCurrentstateCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.IsmTransition_CurrentState_Name
	 * @mbggenerated
	 */
	private String ismtransitionCurrentstateName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.Medicationname_Code
	 * @mbggenerated
	 */
	private String medicationnameCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.Medicationname_Name
	 * @mbggenerated
	 */
	private String medicationnameName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.Memo
	 * @mbggenerated
	 */
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.PatientIdentifier_Id
	 * @mbggenerated
	 */
	private String patientidentifierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.PerformDateTime
	 * @mbggenerated
	 */
	private Date performdatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.PerformDepartment_Code
	 * @mbggenerated
	 */
	private String performdepartmentCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.PerformDepartment_Name
	 * @mbggenerated
	 */
	private String performdepartmentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.Performer_Code
	 * @mbggenerated
	 */
	private String performerCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_DispensingDrugs.Performer_Name
	 * @mbggenerated
	 */
	private String performerName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.Guid
	 * @return  the value of Action_DispensingDrugs.Guid
	 * @mbggenerated
	 */
	public String getGuid() {
		return guid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.Guid
	 * @param guid  the value for Action_DispensingDrugs.Guid
	 * @mbggenerated
	 */
	public void setGuid(String guid) {
		this.guid = guid == null ? null : guid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.DrugsDispensingRequestIdentifier
	 * @return  the value of Action_DispensingDrugs.DrugsDispensingRequestIdentifier
	 * @mbggenerated
	 */
	public String getDrugsdispensingrequestidentifier() {
		return drugsdispensingrequestidentifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.DrugsDispensingRequestIdentifier
	 * @param drugsdispensingrequestidentifier  the value for Action_DispensingDrugs.DrugsDispensingRequestIdentifier
	 * @mbggenerated
	 */
	public void setDrugsdispensingrequestidentifier(
			String drugsdispensingrequestidentifier) {
		this.drugsdispensingrequestidentifier = drugsdispensingrequestidentifier == null ? null
				: drugsdispensingrequestidentifier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.EncounterIdentifier
	 * @return  the value of Action_DispensingDrugs.EncounterIdentifier
	 * @mbggenerated
	 */
	public String getEncounteridentifier() {
		return encounteridentifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.EncounterIdentifier
	 * @param encounteridentifier  the value for Action_DispensingDrugs.EncounterIdentifier
	 * @mbggenerated
	 */
	public void setEncounteridentifier(String encounteridentifier) {
		this.encounteridentifier = encounteridentifier == null ? null
				: encounteridentifier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.IsmTransition_CareflowStep_Code
	 * @return  the value of Action_DispensingDrugs.IsmTransition_CareflowStep_Code
	 * @mbggenerated
	 */
	public String getIsmtransitionCareflowstepCode() {
		return ismtransitionCareflowstepCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.IsmTransition_CareflowStep_Code
	 * @param ismtransitionCareflowstepCode  the value for Action_DispensingDrugs.IsmTransition_CareflowStep_Code
	 * @mbggenerated
	 */
	public void setIsmtransitionCareflowstepCode(
			String ismtransitionCareflowstepCode) {
		this.ismtransitionCareflowstepCode = ismtransitionCareflowstepCode == null ? null
				: ismtransitionCareflowstepCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.IsmTransition_CareflowStep_Name
	 * @return  the value of Action_DispensingDrugs.IsmTransition_CareflowStep_Name
	 * @mbggenerated
	 */
	public String getIsmtransitionCareflowstepName() {
		return ismtransitionCareflowstepName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.IsmTransition_CareflowStep_Name
	 * @param ismtransitionCareflowstepName  the value for Action_DispensingDrugs.IsmTransition_CareflowStep_Name
	 * @mbggenerated
	 */
	public void setIsmtransitionCareflowstepName(
			String ismtransitionCareflowstepName) {
		this.ismtransitionCareflowstepName = ismtransitionCareflowstepName == null ? null
				: ismtransitionCareflowstepName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.IsmTransition_CurrentState_Code
	 * @return  the value of Action_DispensingDrugs.IsmTransition_CurrentState_Code
	 * @mbggenerated
	 */
	public String getIsmtransitionCurrentstateCode() {
		return ismtransitionCurrentstateCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.IsmTransition_CurrentState_Code
	 * @param ismtransitionCurrentstateCode  the value for Action_DispensingDrugs.IsmTransition_CurrentState_Code
	 * @mbggenerated
	 */
	public void setIsmtransitionCurrentstateCode(
			String ismtransitionCurrentstateCode) {
		this.ismtransitionCurrentstateCode = ismtransitionCurrentstateCode == null ? null
				: ismtransitionCurrentstateCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.IsmTransition_CurrentState_Name
	 * @return  the value of Action_DispensingDrugs.IsmTransition_CurrentState_Name
	 * @mbggenerated
	 */
	public String getIsmtransitionCurrentstateName() {
		return ismtransitionCurrentstateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.IsmTransition_CurrentState_Name
	 * @param ismtransitionCurrentstateName  the value for Action_DispensingDrugs.IsmTransition_CurrentState_Name
	 * @mbggenerated
	 */
	public void setIsmtransitionCurrentstateName(
			String ismtransitionCurrentstateName) {
		this.ismtransitionCurrentstateName = ismtransitionCurrentstateName == null ? null
				: ismtransitionCurrentstateName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.Medicationname_Code
	 * @return  the value of Action_DispensingDrugs.Medicationname_Code
	 * @mbggenerated
	 */
	public String getMedicationnameCode() {
		return medicationnameCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.Medicationname_Code
	 * @param medicationnameCode  the value for Action_DispensingDrugs.Medicationname_Code
	 * @mbggenerated
	 */
	public void setMedicationnameCode(String medicationnameCode) {
		this.medicationnameCode = medicationnameCode == null ? null
				: medicationnameCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.Medicationname_Name
	 * @return  the value of Action_DispensingDrugs.Medicationname_Name
	 * @mbggenerated
	 */
	public String getMedicationnameName() {
		return medicationnameName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.Medicationname_Name
	 * @param medicationnameName  the value for Action_DispensingDrugs.Medicationname_Name
	 * @mbggenerated
	 */
	public void setMedicationnameName(String medicationnameName) {
		this.medicationnameName = medicationnameName == null ? null
				: medicationnameName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.Memo
	 * @return  the value of Action_DispensingDrugs.Memo
	 * @mbggenerated
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.Memo
	 * @param memo  the value for Action_DispensingDrugs.Memo
	 * @mbggenerated
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.PatientIdentifier_Id
	 * @return  the value of Action_DispensingDrugs.PatientIdentifier_Id
	 * @mbggenerated
	 */
	public String getPatientidentifierId() {
		return patientidentifierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.PatientIdentifier_Id
	 * @param patientidentifierId  the value for Action_DispensingDrugs.PatientIdentifier_Id
	 * @mbggenerated
	 */
	public void setPatientidentifierId(String patientidentifierId) {
		this.patientidentifierId = patientidentifierId == null ? null
				: patientidentifierId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.PerformDateTime
	 * @return  the value of Action_DispensingDrugs.PerformDateTime
	 * @mbggenerated
	 */
	public Date getPerformdatetime() {
		return performdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.PerformDateTime
	 * @param performdatetime  the value for Action_DispensingDrugs.PerformDateTime
	 * @mbggenerated
	 */
	public void setPerformdatetime(Date performdatetime) {
		this.performdatetime = performdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.PerformDepartment_Code
	 * @return  the value of Action_DispensingDrugs.PerformDepartment_Code
	 * @mbggenerated
	 */
	public String getPerformdepartmentCode() {
		return performdepartmentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.PerformDepartment_Code
	 * @param performdepartmentCode  the value for Action_DispensingDrugs.PerformDepartment_Code
	 * @mbggenerated
	 */
	public void setPerformdepartmentCode(String performdepartmentCode) {
		this.performdepartmentCode = performdepartmentCode == null ? null
				: performdepartmentCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.PerformDepartment_Name
	 * @return  the value of Action_DispensingDrugs.PerformDepartment_Name
	 * @mbggenerated
	 */
	public String getPerformdepartmentName() {
		return performdepartmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.PerformDepartment_Name
	 * @param performdepartmentName  the value for Action_DispensingDrugs.PerformDepartment_Name
	 * @mbggenerated
	 */
	public void setPerformdepartmentName(String performdepartmentName) {
		this.performdepartmentName = performdepartmentName == null ? null
				: performdepartmentName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.Performer_Code
	 * @return  the value of Action_DispensingDrugs.Performer_Code
	 * @mbggenerated
	 */
	public String getPerformerCode() {
		return performerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.Performer_Code
	 * @param performerCode  the value for Action_DispensingDrugs.Performer_Code
	 * @mbggenerated
	 */
	public void setPerformerCode(String performerCode) {
		this.performerCode = performerCode == null ? null : performerCode
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_DispensingDrugs.Performer_Name
	 * @return  the value of Action_DispensingDrugs.Performer_Name
	 * @mbggenerated
	 */
	public String getPerformerName() {
		return performerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_DispensingDrugs.Performer_Name
	 * @param performerName  the value for Action_DispensingDrugs.Performer_Name
	 * @mbggenerated
	 */
	public void setPerformerName(String performerName) {
		this.performerName = performerName == null ? null : performerName
				.trim();
	}
}