package com.test.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderStatusInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    public OrderStatusInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGuidIsNull() {
            addCriterion("Guid is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("Guid is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("Guid =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("Guid <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("Guid >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("Guid >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("Guid <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("Guid <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("Guid like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("Guid not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("Guid in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("Guid not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("Guid between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("Guid not between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andEncounteridentifierIsNull() {
            addCriterion("EncounterIdentifier is null");
            return (Criteria) this;
        }

        public Criteria andEncounteridentifierIsNotNull() {
            addCriterion("EncounterIdentifier is not null");
            return (Criteria) this;
        }

        public Criteria andEncounteridentifierEqualTo(String value) {
            addCriterion("EncounterIdentifier =", value, "encounteridentifier");
            return (Criteria) this;
        }

        public Criteria andEncounteridentifierNotEqualTo(String value) {
            addCriterion("EncounterIdentifier <>", value, "encounteridentifier");
            return (Criteria) this;
        }

        public Criteria andEncounteridentifierGreaterThan(String value) {
            addCriterion("EncounterIdentifier >", value, "encounteridentifier");
            return (Criteria) this;
        }

        public Criteria andEncounteridentifierGreaterThanOrEqualTo(String value) {
            addCriterion("EncounterIdentifier >=", value, "encounteridentifier");
            return (Criteria) this;
        }

        public Criteria andEncounteridentifierLessThan(String value) {
            addCriterion("EncounterIdentifier <", value, "encounteridentifier");
            return (Criteria) this;
        }

        public Criteria andEncounteridentifierLessThanOrEqualTo(String value) {
            addCriterion("EncounterIdentifier <=", value, "encounteridentifier");
            return (Criteria) this;
        }

        public Criteria andEncounteridentifierLike(String value) {
            addCriterion("EncounterIdentifier like", value, "encounteridentifier");
            return (Criteria) this;
        }

        public Criteria andEncounteridentifierNotLike(String value) {
            addCriterion("EncounterIdentifier not like", value, "encounteridentifier");
            return (Criteria) this;
        }

        public Criteria andEncounteridentifierIn(List<String> values) {
            addCriterion("EncounterIdentifier in", values, "encounteridentifier");
            return (Criteria) this;
        }

        public Criteria andEncounteridentifierNotIn(List<String> values) {
            addCriterion("EncounterIdentifier not in", values, "encounteridentifier");
            return (Criteria) this;
        }

        public Criteria andEncounteridentifierBetween(String value1, String value2) {
            addCriterion("EncounterIdentifier between", value1, value2, "encounteridentifier");
            return (Criteria) this;
        }

        public Criteria andEncounteridentifierNotBetween(String value1, String value2) {
            addCriterion("EncounterIdentifier not between", value1, value2, "encounteridentifier");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepCodeIsNull() {
            addCriterion("IsmTransition_CareflowStep_Code is null");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepCodeIsNotNull() {
            addCriterion("IsmTransition_CareflowStep_Code is not null");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepCodeEqualTo(String value) {
            addCriterion("IsmTransition_CareflowStep_Code =", value, "ismtransitionCareflowstepCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepCodeNotEqualTo(String value) {
            addCriterion("IsmTransition_CareflowStep_Code <>", value, "ismtransitionCareflowstepCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepCodeGreaterThan(String value) {
            addCriterion("IsmTransition_CareflowStep_Code >", value, "ismtransitionCareflowstepCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepCodeGreaterThanOrEqualTo(String value) {
            addCriterion("IsmTransition_CareflowStep_Code >=", value, "ismtransitionCareflowstepCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepCodeLessThan(String value) {
            addCriterion("IsmTransition_CareflowStep_Code <", value, "ismtransitionCareflowstepCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepCodeLessThanOrEqualTo(String value) {
            addCriterion("IsmTransition_CareflowStep_Code <=", value, "ismtransitionCareflowstepCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepCodeLike(String value) {
            addCriterion("IsmTransition_CareflowStep_Code like", value, "ismtransitionCareflowstepCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepCodeNotLike(String value) {
            addCriterion("IsmTransition_CareflowStep_Code not like", value, "ismtransitionCareflowstepCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepCodeIn(List<String> values) {
            addCriterion("IsmTransition_CareflowStep_Code in", values, "ismtransitionCareflowstepCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepCodeNotIn(List<String> values) {
            addCriterion("IsmTransition_CareflowStep_Code not in", values, "ismtransitionCareflowstepCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepCodeBetween(String value1, String value2) {
            addCriterion("IsmTransition_CareflowStep_Code between", value1, value2, "ismtransitionCareflowstepCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepCodeNotBetween(String value1, String value2) {
            addCriterion("IsmTransition_CareflowStep_Code not between", value1, value2, "ismtransitionCareflowstepCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepNameIsNull() {
            addCriterion("IsmTransition_CareflowStep_Name is null");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepNameIsNotNull() {
            addCriterion("IsmTransition_CareflowStep_Name is not null");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepNameEqualTo(String value) {
            addCriterion("IsmTransition_CareflowStep_Name =", value, "ismtransitionCareflowstepName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepNameNotEqualTo(String value) {
            addCriterion("IsmTransition_CareflowStep_Name <>", value, "ismtransitionCareflowstepName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepNameGreaterThan(String value) {
            addCriterion("IsmTransition_CareflowStep_Name >", value, "ismtransitionCareflowstepName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepNameGreaterThanOrEqualTo(String value) {
            addCriterion("IsmTransition_CareflowStep_Name >=", value, "ismtransitionCareflowstepName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepNameLessThan(String value) {
            addCriterion("IsmTransition_CareflowStep_Name <", value, "ismtransitionCareflowstepName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepNameLessThanOrEqualTo(String value) {
            addCriterion("IsmTransition_CareflowStep_Name <=", value, "ismtransitionCareflowstepName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepNameLike(String value) {
            addCriterion("IsmTransition_CareflowStep_Name like", value, "ismtransitionCareflowstepName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepNameNotLike(String value) {
            addCriterion("IsmTransition_CareflowStep_Name not like", value, "ismtransitionCareflowstepName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepNameIn(List<String> values) {
            addCriterion("IsmTransition_CareflowStep_Name in", values, "ismtransitionCareflowstepName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepNameNotIn(List<String> values) {
            addCriterion("IsmTransition_CareflowStep_Name not in", values, "ismtransitionCareflowstepName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepNameBetween(String value1, String value2) {
            addCriterion("IsmTransition_CareflowStep_Name between", value1, value2, "ismtransitionCareflowstepName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCareflowstepNameNotBetween(String value1, String value2) {
            addCriterion("IsmTransition_CareflowStep_Name not between", value1, value2, "ismtransitionCareflowstepName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateCodeIsNull() {
            addCriterion("IsmTransition_CurrentState_Code is null");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateCodeIsNotNull() {
            addCriterion("IsmTransition_CurrentState_Code is not null");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateCodeEqualTo(String value) {
            addCriterion("IsmTransition_CurrentState_Code =", value, "ismtransitionCurrentstateCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateCodeNotEqualTo(String value) {
            addCriterion("IsmTransition_CurrentState_Code <>", value, "ismtransitionCurrentstateCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateCodeGreaterThan(String value) {
            addCriterion("IsmTransition_CurrentState_Code >", value, "ismtransitionCurrentstateCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateCodeGreaterThanOrEqualTo(String value) {
            addCriterion("IsmTransition_CurrentState_Code >=", value, "ismtransitionCurrentstateCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateCodeLessThan(String value) {
            addCriterion("IsmTransition_CurrentState_Code <", value, "ismtransitionCurrentstateCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateCodeLessThanOrEqualTo(String value) {
            addCriterion("IsmTransition_CurrentState_Code <=", value, "ismtransitionCurrentstateCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateCodeLike(String value) {
            addCriterion("IsmTransition_CurrentState_Code like", value, "ismtransitionCurrentstateCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateCodeNotLike(String value) {
            addCriterion("IsmTransition_CurrentState_Code not like", value, "ismtransitionCurrentstateCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateCodeIn(List<String> values) {
            addCriterion("IsmTransition_CurrentState_Code in", values, "ismtransitionCurrentstateCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateCodeNotIn(List<String> values) {
            addCriterion("IsmTransition_CurrentState_Code not in", values, "ismtransitionCurrentstateCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateCodeBetween(String value1, String value2) {
            addCriterion("IsmTransition_CurrentState_Code between", value1, value2, "ismtransitionCurrentstateCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateCodeNotBetween(String value1, String value2) {
            addCriterion("IsmTransition_CurrentState_Code not between", value1, value2, "ismtransitionCurrentstateCode");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateNameIsNull() {
            addCriterion("IsmTransition_CurrentState_Name is null");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateNameIsNotNull() {
            addCriterion("IsmTransition_CurrentState_Name is not null");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateNameEqualTo(String value) {
            addCriterion("IsmTransition_CurrentState_Name =", value, "ismtransitionCurrentstateName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateNameNotEqualTo(String value) {
            addCriterion("IsmTransition_CurrentState_Name <>", value, "ismtransitionCurrentstateName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateNameGreaterThan(String value) {
            addCriterion("IsmTransition_CurrentState_Name >", value, "ismtransitionCurrentstateName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateNameGreaterThanOrEqualTo(String value) {
            addCriterion("IsmTransition_CurrentState_Name >=", value, "ismtransitionCurrentstateName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateNameLessThan(String value) {
            addCriterion("IsmTransition_CurrentState_Name <", value, "ismtransitionCurrentstateName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateNameLessThanOrEqualTo(String value) {
            addCriterion("IsmTransition_CurrentState_Name <=", value, "ismtransitionCurrentstateName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateNameLike(String value) {
            addCriterion("IsmTransition_CurrentState_Name like", value, "ismtransitionCurrentstateName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateNameNotLike(String value) {
            addCriterion("IsmTransition_CurrentState_Name not like", value, "ismtransitionCurrentstateName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateNameIn(List<String> values) {
            addCriterion("IsmTransition_CurrentState_Name in", values, "ismtransitionCurrentstateName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateNameNotIn(List<String> values) {
            addCriterion("IsmTransition_CurrentState_Name not in", values, "ismtransitionCurrentstateName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateNameBetween(String value1, String value2) {
            addCriterion("IsmTransition_CurrentState_Name between", value1, value2, "ismtransitionCurrentstateName");
            return (Criteria) this;
        }

        public Criteria andIsmtransitionCurrentstateNameNotBetween(String value1, String value2) {
            addCriterion("IsmTransition_CurrentState_Name not between", value1, value2, "ismtransitionCurrentstateName");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("Memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("Memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("Memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("Memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("Memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("Memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("Memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("Memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("Memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("Memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("Memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("Memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("Memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("Memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andOrderidentifierIsNull() {
            addCriterion("OrderIdentifier is null");
            return (Criteria) this;
        }

        public Criteria andOrderidentifierIsNotNull() {
            addCriterion("OrderIdentifier is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidentifierEqualTo(String value) {
            addCriterion("OrderIdentifier =", value, "orderidentifier");
            return (Criteria) this;
        }

        public Criteria andOrderidentifierNotEqualTo(String value) {
            addCriterion("OrderIdentifier <>", value, "orderidentifier");
            return (Criteria) this;
        }

        public Criteria andOrderidentifierGreaterThan(String value) {
            addCriterion("OrderIdentifier >", value, "orderidentifier");
            return (Criteria) this;
        }

        public Criteria andOrderidentifierGreaterThanOrEqualTo(String value) {
            addCriterion("OrderIdentifier >=", value, "orderidentifier");
            return (Criteria) this;
        }

        public Criteria andOrderidentifierLessThan(String value) {
            addCriterion("OrderIdentifier <", value, "orderidentifier");
            return (Criteria) this;
        }

        public Criteria andOrderidentifierLessThanOrEqualTo(String value) {
            addCriterion("OrderIdentifier <=", value, "orderidentifier");
            return (Criteria) this;
        }

        public Criteria andOrderidentifierLike(String value) {
            addCriterion("OrderIdentifier like", value, "orderidentifier");
            return (Criteria) this;
        }

        public Criteria andOrderidentifierNotLike(String value) {
            addCriterion("OrderIdentifier not like", value, "orderidentifier");
            return (Criteria) this;
        }

        public Criteria andOrderidentifierIn(List<String> values) {
            addCriterion("OrderIdentifier in", values, "orderidentifier");
            return (Criteria) this;
        }

        public Criteria andOrderidentifierNotIn(List<String> values) {
            addCriterion("OrderIdentifier not in", values, "orderidentifier");
            return (Criteria) this;
        }

        public Criteria andOrderidentifierBetween(String value1, String value2) {
            addCriterion("OrderIdentifier between", value1, value2, "orderidentifier");
            return (Criteria) this;
        }

        public Criteria andOrderidentifierNotBetween(String value1, String value2) {
            addCriterion("OrderIdentifier not between", value1, value2, "orderidentifier");
            return (Criteria) this;
        }

        public Criteria andOrderitemIsNull() {
            addCriterion("OrderItem is null");
            return (Criteria) this;
        }

        public Criteria andOrderitemIsNotNull() {
            addCriterion("OrderItem is not null");
            return (Criteria) this;
        }

        public Criteria andOrderitemEqualTo(String value) {
            addCriterion("OrderItem =", value, "orderitem");
            return (Criteria) this;
        }

        public Criteria andOrderitemNotEqualTo(String value) {
            addCriterion("OrderItem <>", value, "orderitem");
            return (Criteria) this;
        }

        public Criteria andOrderitemGreaterThan(String value) {
            addCriterion("OrderItem >", value, "orderitem");
            return (Criteria) this;
        }

        public Criteria andOrderitemGreaterThanOrEqualTo(String value) {
            addCriterion("OrderItem >=", value, "orderitem");
            return (Criteria) this;
        }

        public Criteria andOrderitemLessThan(String value) {
            addCriterion("OrderItem <", value, "orderitem");
            return (Criteria) this;
        }

        public Criteria andOrderitemLessThanOrEqualTo(String value) {
            addCriterion("OrderItem <=", value, "orderitem");
            return (Criteria) this;
        }

        public Criteria andOrderitemLike(String value) {
            addCriterion("OrderItem like", value, "orderitem");
            return (Criteria) this;
        }

        public Criteria andOrderitemNotLike(String value) {
            addCriterion("OrderItem not like", value, "orderitem");
            return (Criteria) this;
        }

        public Criteria andOrderitemIn(List<String> values) {
            addCriterion("OrderItem in", values, "orderitem");
            return (Criteria) this;
        }

        public Criteria andOrderitemNotIn(List<String> values) {
            addCriterion("OrderItem not in", values, "orderitem");
            return (Criteria) this;
        }

        public Criteria andOrderitemBetween(String value1, String value2) {
            addCriterion("OrderItem between", value1, value2, "orderitem");
            return (Criteria) this;
        }

        public Criteria andOrderitemNotBetween(String value1, String value2) {
            addCriterion("OrderItem not between", value1, value2, "orderitem");
            return (Criteria) this;
        }

        public Criteria andPatientidentifierIdIsNull() {
            addCriterion("PatientIdentifier_Id is null");
            return (Criteria) this;
        }

        public Criteria andPatientidentifierIdIsNotNull() {
            addCriterion("PatientIdentifier_Id is not null");
            return (Criteria) this;
        }

        public Criteria andPatientidentifierIdEqualTo(String value) {
            addCriterion("PatientIdentifier_Id =", value, "patientidentifierId");
            return (Criteria) this;
        }

        public Criteria andPatientidentifierIdNotEqualTo(String value) {
            addCriterion("PatientIdentifier_Id <>", value, "patientidentifierId");
            return (Criteria) this;
        }

        public Criteria andPatientidentifierIdGreaterThan(String value) {
            addCriterion("PatientIdentifier_Id >", value, "patientidentifierId");
            return (Criteria) this;
        }

        public Criteria andPatientidentifierIdGreaterThanOrEqualTo(String value) {
            addCriterion("PatientIdentifier_Id >=", value, "patientidentifierId");
            return (Criteria) this;
        }

        public Criteria andPatientidentifierIdLessThan(String value) {
            addCriterion("PatientIdentifier_Id <", value, "patientidentifierId");
            return (Criteria) this;
        }

        public Criteria andPatientidentifierIdLessThanOrEqualTo(String value) {
            addCriterion("PatientIdentifier_Id <=", value, "patientidentifierId");
            return (Criteria) this;
        }

        public Criteria andPatientidentifierIdLike(String value) {
            addCriterion("PatientIdentifier_Id like", value, "patientidentifierId");
            return (Criteria) this;
        }

        public Criteria andPatientidentifierIdNotLike(String value) {
            addCriterion("PatientIdentifier_Id not like", value, "patientidentifierId");
            return (Criteria) this;
        }

        public Criteria andPatientidentifierIdIn(List<String> values) {
            addCriterion("PatientIdentifier_Id in", values, "patientidentifierId");
            return (Criteria) this;
        }

        public Criteria andPatientidentifierIdNotIn(List<String> values) {
            addCriterion("PatientIdentifier_Id not in", values, "patientidentifierId");
            return (Criteria) this;
        }

        public Criteria andPatientidentifierIdBetween(String value1, String value2) {
            addCriterion("PatientIdentifier_Id between", value1, value2, "patientidentifierId");
            return (Criteria) this;
        }

        public Criteria andPatientidentifierIdNotBetween(String value1, String value2) {
            addCriterion("PatientIdentifier_Id not between", value1, value2, "patientidentifierId");
            return (Criteria) this;
        }

        public Criteria andPerformdatetimeIsNull() {
            addCriterion("PerformDateTime is null");
            return (Criteria) this;
        }

        public Criteria andPerformdatetimeIsNotNull() {
            addCriterion("PerformDateTime is not null");
            return (Criteria) this;
        }

        public Criteria andPerformdatetimeEqualTo(Date value) {
            addCriterion("PerformDateTime =", value, "performdatetime");
            return (Criteria) this;
        }

        public Criteria andPerformdatetimeNotEqualTo(Date value) {
            addCriterion("PerformDateTime <>", value, "performdatetime");
            return (Criteria) this;
        }

        public Criteria andPerformdatetimeGreaterThan(Date value) {
            addCriterion("PerformDateTime >", value, "performdatetime");
            return (Criteria) this;
        }

        public Criteria andPerformdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PerformDateTime >=", value, "performdatetime");
            return (Criteria) this;
        }

        public Criteria andPerformdatetimeLessThan(Date value) {
            addCriterion("PerformDateTime <", value, "performdatetime");
            return (Criteria) this;
        }

        public Criteria andPerformdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("PerformDateTime <=", value, "performdatetime");
            return (Criteria) this;
        }

        public Criteria andPerformdatetimeIn(List<Date> values) {
            addCriterion("PerformDateTime in", values, "performdatetime");
            return (Criteria) this;
        }

        public Criteria andPerformdatetimeNotIn(List<Date> values) {
            addCriterion("PerformDateTime not in", values, "performdatetime");
            return (Criteria) this;
        }

        public Criteria andPerformdatetimeBetween(Date value1, Date value2) {
            addCriterion("PerformDateTime between", value1, value2, "performdatetime");
            return (Criteria) this;
        }

        public Criteria andPerformdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("PerformDateTime not between", value1, value2, "performdatetime");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentCodeIsNull() {
            addCriterion("PerformDepartment_Code is null");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentCodeIsNotNull() {
            addCriterion("PerformDepartment_Code is not null");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentCodeEqualTo(String value) {
            addCriterion("PerformDepartment_Code =", value, "performdepartmentCode");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentCodeNotEqualTo(String value) {
            addCriterion("PerformDepartment_Code <>", value, "performdepartmentCode");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentCodeGreaterThan(String value) {
            addCriterion("PerformDepartment_Code >", value, "performdepartmentCode");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PerformDepartment_Code >=", value, "performdepartmentCode");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentCodeLessThan(String value) {
            addCriterion("PerformDepartment_Code <", value, "performdepartmentCode");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentCodeLessThanOrEqualTo(String value) {
            addCriterion("PerformDepartment_Code <=", value, "performdepartmentCode");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentCodeLike(String value) {
            addCriterion("PerformDepartment_Code like", value, "performdepartmentCode");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentCodeNotLike(String value) {
            addCriterion("PerformDepartment_Code not like", value, "performdepartmentCode");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentCodeIn(List<String> values) {
            addCriterion("PerformDepartment_Code in", values, "performdepartmentCode");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentCodeNotIn(List<String> values) {
            addCriterion("PerformDepartment_Code not in", values, "performdepartmentCode");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentCodeBetween(String value1, String value2) {
            addCriterion("PerformDepartment_Code between", value1, value2, "performdepartmentCode");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentCodeNotBetween(String value1, String value2) {
            addCriterion("PerformDepartment_Code not between", value1, value2, "performdepartmentCode");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentNameIsNull() {
            addCriterion("PerformDepartment_Name is null");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentNameIsNotNull() {
            addCriterion("PerformDepartment_Name is not null");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentNameEqualTo(String value) {
            addCriterion("PerformDepartment_Name =", value, "performdepartmentName");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentNameNotEqualTo(String value) {
            addCriterion("PerformDepartment_Name <>", value, "performdepartmentName");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentNameGreaterThan(String value) {
            addCriterion("PerformDepartment_Name >", value, "performdepartmentName");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentNameGreaterThanOrEqualTo(String value) {
            addCriterion("PerformDepartment_Name >=", value, "performdepartmentName");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentNameLessThan(String value) {
            addCriterion("PerformDepartment_Name <", value, "performdepartmentName");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentNameLessThanOrEqualTo(String value) {
            addCriterion("PerformDepartment_Name <=", value, "performdepartmentName");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentNameLike(String value) {
            addCriterion("PerformDepartment_Name like", value, "performdepartmentName");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentNameNotLike(String value) {
            addCriterion("PerformDepartment_Name not like", value, "performdepartmentName");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentNameIn(List<String> values) {
            addCriterion("PerformDepartment_Name in", values, "performdepartmentName");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentNameNotIn(List<String> values) {
            addCriterion("PerformDepartment_Name not in", values, "performdepartmentName");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentNameBetween(String value1, String value2) {
            addCriterion("PerformDepartment_Name between", value1, value2, "performdepartmentName");
            return (Criteria) this;
        }

        public Criteria andPerformdepartmentNameNotBetween(String value1, String value2) {
            addCriterion("PerformDepartment_Name not between", value1, value2, "performdepartmentName");
            return (Criteria) this;
        }

        public Criteria andPerformerCodeIsNull() {
            addCriterion("Performer_Code is null");
            return (Criteria) this;
        }

        public Criteria andPerformerCodeIsNotNull() {
            addCriterion("Performer_Code is not null");
            return (Criteria) this;
        }

        public Criteria andPerformerCodeEqualTo(String value) {
            addCriterion("Performer_Code =", value, "performerCode");
            return (Criteria) this;
        }

        public Criteria andPerformerCodeNotEqualTo(String value) {
            addCriterion("Performer_Code <>", value, "performerCode");
            return (Criteria) this;
        }

        public Criteria andPerformerCodeGreaterThan(String value) {
            addCriterion("Performer_Code >", value, "performerCode");
            return (Criteria) this;
        }

        public Criteria andPerformerCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Performer_Code >=", value, "performerCode");
            return (Criteria) this;
        }

        public Criteria andPerformerCodeLessThan(String value) {
            addCriterion("Performer_Code <", value, "performerCode");
            return (Criteria) this;
        }

        public Criteria andPerformerCodeLessThanOrEqualTo(String value) {
            addCriterion("Performer_Code <=", value, "performerCode");
            return (Criteria) this;
        }

        public Criteria andPerformerCodeLike(String value) {
            addCriterion("Performer_Code like", value, "performerCode");
            return (Criteria) this;
        }

        public Criteria andPerformerCodeNotLike(String value) {
            addCriterion("Performer_Code not like", value, "performerCode");
            return (Criteria) this;
        }

        public Criteria andPerformerCodeIn(List<String> values) {
            addCriterion("Performer_Code in", values, "performerCode");
            return (Criteria) this;
        }

        public Criteria andPerformerCodeNotIn(List<String> values) {
            addCriterion("Performer_Code not in", values, "performerCode");
            return (Criteria) this;
        }

        public Criteria andPerformerCodeBetween(String value1, String value2) {
            addCriterion("Performer_Code between", value1, value2, "performerCode");
            return (Criteria) this;
        }

        public Criteria andPerformerCodeNotBetween(String value1, String value2) {
            addCriterion("Performer_Code not between", value1, value2, "performerCode");
            return (Criteria) this;
        }

        public Criteria andPerformerNameIsNull() {
            addCriterion("Performer_Name is null");
            return (Criteria) this;
        }

        public Criteria andPerformerNameIsNotNull() {
            addCriterion("Performer_Name is not null");
            return (Criteria) this;
        }

        public Criteria andPerformerNameEqualTo(String value) {
            addCriterion("Performer_Name =", value, "performerName");
            return (Criteria) this;
        }

        public Criteria andPerformerNameNotEqualTo(String value) {
            addCriterion("Performer_Name <>", value, "performerName");
            return (Criteria) this;
        }

        public Criteria andPerformerNameGreaterThan(String value) {
            addCriterion("Performer_Name >", value, "performerName");
            return (Criteria) this;
        }

        public Criteria andPerformerNameGreaterThanOrEqualTo(String value) {
            addCriterion("Performer_Name >=", value, "performerName");
            return (Criteria) this;
        }

        public Criteria andPerformerNameLessThan(String value) {
            addCriterion("Performer_Name <", value, "performerName");
            return (Criteria) this;
        }

        public Criteria andPerformerNameLessThanOrEqualTo(String value) {
            addCriterion("Performer_Name <=", value, "performerName");
            return (Criteria) this;
        }

        public Criteria andPerformerNameLike(String value) {
            addCriterion("Performer_Name like", value, "performerName");
            return (Criteria) this;
        }

        public Criteria andPerformerNameNotLike(String value) {
            addCriterion("Performer_Name not like", value, "performerName");
            return (Criteria) this;
        }

        public Criteria andPerformerNameIn(List<String> values) {
            addCriterion("Performer_Name in", values, "performerName");
            return (Criteria) this;
        }

        public Criteria andPerformerNameNotIn(List<String> values) {
            addCriterion("Performer_Name not in", values, "performerName");
            return (Criteria) this;
        }

        public Criteria andPerformerNameBetween(String value1, String value2) {
            addCriterion("Performer_Name between", value1, value2, "performerName");
            return (Criteria) this;
        }

        public Criteria andPerformerNameNotBetween(String value1, String value2) {
            addCriterion("Performer_Name not between", value1, value2, "performerName");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeCodeIsNull() {
            addCriterion("PersonnelType_Code is null");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeCodeIsNotNull() {
            addCriterion("PersonnelType_Code is not null");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeCodeEqualTo(String value) {
            addCriterion("PersonnelType_Code =", value, "personneltypeCode");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeCodeNotEqualTo(String value) {
            addCriterion("PersonnelType_Code <>", value, "personneltypeCode");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeCodeGreaterThan(String value) {
            addCriterion("PersonnelType_Code >", value, "personneltypeCode");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PersonnelType_Code >=", value, "personneltypeCode");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeCodeLessThan(String value) {
            addCriterion("PersonnelType_Code <", value, "personneltypeCode");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeCodeLessThanOrEqualTo(String value) {
            addCriterion("PersonnelType_Code <=", value, "personneltypeCode");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeCodeLike(String value) {
            addCriterion("PersonnelType_Code like", value, "personneltypeCode");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeCodeNotLike(String value) {
            addCriterion("PersonnelType_Code not like", value, "personneltypeCode");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeCodeIn(List<String> values) {
            addCriterion("PersonnelType_Code in", values, "personneltypeCode");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeCodeNotIn(List<String> values) {
            addCriterion("PersonnelType_Code not in", values, "personneltypeCode");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeCodeBetween(String value1, String value2) {
            addCriterion("PersonnelType_Code between", value1, value2, "personneltypeCode");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeCodeNotBetween(String value1, String value2) {
            addCriterion("PersonnelType_Code not between", value1, value2, "personneltypeCode");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeNameIsNull() {
            addCriterion("PersonnelType_Name is null");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeNameIsNotNull() {
            addCriterion("PersonnelType_Name is not null");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeNameEqualTo(String value) {
            addCriterion("PersonnelType_Name =", value, "personneltypeName");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeNameNotEqualTo(String value) {
            addCriterion("PersonnelType_Name <>", value, "personneltypeName");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeNameGreaterThan(String value) {
            addCriterion("PersonnelType_Name >", value, "personneltypeName");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("PersonnelType_Name >=", value, "personneltypeName");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeNameLessThan(String value) {
            addCriterion("PersonnelType_Name <", value, "personneltypeName");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeNameLessThanOrEqualTo(String value) {
            addCriterion("PersonnelType_Name <=", value, "personneltypeName");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeNameLike(String value) {
            addCriterion("PersonnelType_Name like", value, "personneltypeName");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeNameNotLike(String value) {
            addCriterion("PersonnelType_Name not like", value, "personneltypeName");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeNameIn(List<String> values) {
            addCriterion("PersonnelType_Name in", values, "personneltypeName");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeNameNotIn(List<String> values) {
            addCriterion("PersonnelType_Name not in", values, "personneltypeName");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeNameBetween(String value1, String value2) {
            addCriterion("PersonnelType_Name between", value1, value2, "personneltypeName");
            return (Criteria) this;
        }

        public Criteria andPersonneltypeNameNotBetween(String value1, String value2) {
            addCriterion("PersonnelType_Name not between", value1, value2, "personneltypeName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Action_Order
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Action_Order
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}