package com.test.mybatis.model;

import java.util.Date;

public class OrderStatusInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.Guid
	 * @mbggenerated
	 */
	private String guid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.EncounterIdentifier
	 * @mbggenerated
	 */
	private String encounteridentifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.IsmTransition_CareflowStep_Code
	 * @mbggenerated
	 */
	private String ismtransitionCareflowstepCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.IsmTransition_CareflowStep_Name
	 * @mbggenerated
	 */
	private String ismtransitionCareflowstepName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.IsmTransition_CurrentState_Code
	 * @mbggenerated
	 */
	private String ismtransitionCurrentstateCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.IsmTransition_CurrentState_Name
	 * @mbggenerated
	 */
	private String ismtransitionCurrentstateName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.Memo
	 * @mbggenerated
	 */
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.OrderIdentifier
	 * @mbggenerated
	 */
	private String orderidentifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.OrderItem
	 * @mbggenerated
	 */
	private String orderitem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.PatientIdentifier_Id
	 * @mbggenerated
	 */
	private String patientidentifierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.PerformDateTime
	 * @mbggenerated
	 */
	private Date performdatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.PerformDepartment_Code
	 * @mbggenerated
	 */
	private String performdepartmentCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.PerformDepartment_Name
	 * @mbggenerated
	 */
	private String performdepartmentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.Performer_Code
	 * @mbggenerated
	 */
	private String performerCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.Performer_Name
	 * @mbggenerated
	 */
	private String performerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.PersonnelType_Code
	 * @mbggenerated
	 */
	private String personneltypeCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action_Order.PersonnelType_Name
	 * @mbggenerated
	 */
	private String personneltypeName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.Guid
	 * @return  the value of Action_Order.Guid
	 * @mbggenerated
	 */
	public String getGuid() {
		return guid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.Guid
	 * @param guid  the value for Action_Order.Guid
	 * @mbggenerated
	 */
	public void setGuid(String guid) {
		this.guid = guid == null ? null : guid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.EncounterIdentifier
	 * @return  the value of Action_Order.EncounterIdentifier
	 * @mbggenerated
	 */
	public String getEncounteridentifier() {
		return encounteridentifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.EncounterIdentifier
	 * @param encounteridentifier  the value for Action_Order.EncounterIdentifier
	 * @mbggenerated
	 */
	public void setEncounteridentifier(String encounteridentifier) {
		this.encounteridentifier = encounteridentifier == null ? null
				: encounteridentifier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.IsmTransition_CareflowStep_Code
	 * @return  the value of Action_Order.IsmTransition_CareflowStep_Code
	 * @mbggenerated
	 */
	public String getIsmtransitionCareflowstepCode() {
		return ismtransitionCareflowstepCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.IsmTransition_CareflowStep_Code
	 * @param ismtransitionCareflowstepCode  the value for Action_Order.IsmTransition_CareflowStep_Code
	 * @mbggenerated
	 */
	public void setIsmtransitionCareflowstepCode(
			String ismtransitionCareflowstepCode) {
		this.ismtransitionCareflowstepCode = ismtransitionCareflowstepCode == null ? null
				: ismtransitionCareflowstepCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.IsmTransition_CareflowStep_Name
	 * @return  the value of Action_Order.IsmTransition_CareflowStep_Name
	 * @mbggenerated
	 */
	public String getIsmtransitionCareflowstepName() {
		return ismtransitionCareflowstepName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.IsmTransition_CareflowStep_Name
	 * @param ismtransitionCareflowstepName  the value for Action_Order.IsmTransition_CareflowStep_Name
	 * @mbggenerated
	 */
	public void setIsmtransitionCareflowstepName(
			String ismtransitionCareflowstepName) {
		this.ismtransitionCareflowstepName = ismtransitionCareflowstepName == null ? null
				: ismtransitionCareflowstepName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.IsmTransition_CurrentState_Code
	 * @return  the value of Action_Order.IsmTransition_CurrentState_Code
	 * @mbggenerated
	 */
	public String getIsmtransitionCurrentstateCode() {
		return ismtransitionCurrentstateCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.IsmTransition_CurrentState_Code
	 * @param ismtransitionCurrentstateCode  the value for Action_Order.IsmTransition_CurrentState_Code
	 * @mbggenerated
	 */
	public void setIsmtransitionCurrentstateCode(
			String ismtransitionCurrentstateCode) {
		this.ismtransitionCurrentstateCode = ismtransitionCurrentstateCode == null ? null
				: ismtransitionCurrentstateCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.IsmTransition_CurrentState_Name
	 * @return  the value of Action_Order.IsmTransition_CurrentState_Name
	 * @mbggenerated
	 */
	public String getIsmtransitionCurrentstateName() {
		return ismtransitionCurrentstateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.IsmTransition_CurrentState_Name
	 * @param ismtransitionCurrentstateName  the value for Action_Order.IsmTransition_CurrentState_Name
	 * @mbggenerated
	 */
	public void setIsmtransitionCurrentstateName(
			String ismtransitionCurrentstateName) {
		this.ismtransitionCurrentstateName = ismtransitionCurrentstateName == null ? null
				: ismtransitionCurrentstateName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.Memo
	 * @return  the value of Action_Order.Memo
	 * @mbggenerated
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.Memo
	 * @param memo  the value for Action_Order.Memo
	 * @mbggenerated
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.OrderIdentifier
	 * @return  the value of Action_Order.OrderIdentifier
	 * @mbggenerated
	 */
	public String getOrderidentifier() {
		return orderidentifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.OrderIdentifier
	 * @param orderidentifier  the value for Action_Order.OrderIdentifier
	 * @mbggenerated
	 */
	public void setOrderidentifier(String orderidentifier) {
		this.orderidentifier = orderidentifier == null ? null : orderidentifier
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.OrderItem
	 * @return  the value of Action_Order.OrderItem
	 * @mbggenerated
	 */
	public String getOrderitem() {
		return orderitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.OrderItem
	 * @param orderitem  the value for Action_Order.OrderItem
	 * @mbggenerated
	 */
	public void setOrderitem(String orderitem) {
		this.orderitem = orderitem == null ? null : orderitem.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.PatientIdentifier_Id
	 * @return  the value of Action_Order.PatientIdentifier_Id
	 * @mbggenerated
	 */
	public String getPatientidentifierId() {
		return patientidentifierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.PatientIdentifier_Id
	 * @param patientidentifierId  the value for Action_Order.PatientIdentifier_Id
	 * @mbggenerated
	 */
	public void setPatientidentifierId(String patientidentifierId) {
		this.patientidentifierId = patientidentifierId == null ? null
				: patientidentifierId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.PerformDateTime
	 * @return  the value of Action_Order.PerformDateTime
	 * @mbggenerated
	 */
	public Date getPerformdatetime() {
		return performdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.PerformDateTime
	 * @param performdatetime  the value for Action_Order.PerformDateTime
	 * @mbggenerated
	 */
	public void setPerformdatetime(Date performdatetime) {
		this.performdatetime = performdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.PerformDepartment_Code
	 * @return  the value of Action_Order.PerformDepartment_Code
	 * @mbggenerated
	 */
	public String getPerformdepartmentCode() {
		return performdepartmentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.PerformDepartment_Code
	 * @param performdepartmentCode  the value for Action_Order.PerformDepartment_Code
	 * @mbggenerated
	 */
	public void setPerformdepartmentCode(String performdepartmentCode) {
		this.performdepartmentCode = performdepartmentCode == null ? null
				: performdepartmentCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.PerformDepartment_Name
	 * @return  the value of Action_Order.PerformDepartment_Name
	 * @mbggenerated
	 */
	public String getPerformdepartmentName() {
		return performdepartmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.PerformDepartment_Name
	 * @param performdepartmentName  the value for Action_Order.PerformDepartment_Name
	 * @mbggenerated
	 */
	public void setPerformdepartmentName(String performdepartmentName) {
		this.performdepartmentName = performdepartmentName == null ? null
				: performdepartmentName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.Performer_Code
	 * @return  the value of Action_Order.Performer_Code
	 * @mbggenerated
	 */
	public String getPerformerCode() {
		return performerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.Performer_Code
	 * @param performerCode  the value for Action_Order.Performer_Code
	 * @mbggenerated
	 */
	public void setPerformerCode(String performerCode) {
		this.performerCode = performerCode == null ? null : performerCode
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.Performer_Name
	 * @return  the value of Action_Order.Performer_Name
	 * @mbggenerated
	 */
	public String getPerformerName() {
		return performerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.Performer_Name
	 * @param performerName  the value for Action_Order.Performer_Name
	 * @mbggenerated
	 */
	public void setPerformerName(String performerName) {
		this.performerName = performerName == null ? null : performerName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.PersonnelType_Code
	 * @return  the value of Action_Order.PersonnelType_Code
	 * @mbggenerated
	 */
	public String getPersonneltypeCode() {
		return personneltypeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.PersonnelType_Code
	 * @param personneltypeCode  the value for Action_Order.PersonnelType_Code
	 * @mbggenerated
	 */
	public void setPersonneltypeCode(String personneltypeCode) {
		this.personneltypeCode = personneltypeCode == null ? null
				: personneltypeCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action_Order.PersonnelType_Name
	 * @return  the value of Action_Order.PersonnelType_Name
	 * @mbggenerated
	 */
	public String getPersonneltypeName() {
		return personneltypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action_Order.PersonnelType_Name
	 * @param personneltypeName  the value for Action_Order.PersonnelType_Name
	 * @mbggenerated
	 */
	public void setPersonneltypeName(String personneltypeName) {
		this.personneltypeName = personneltypeName == null ? null
				: personneltypeName.trim();
	}
}