package com.test.mybatis.model;

import java.util.Date;

public class PatientVisitInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.Guid
	 * @mbggenerated
	 */
	private String guid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AdmissionType_Code
	 * @mbggenerated
	 */
	private String admissiontypeCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AdmissionType_Name
	 * @mbggenerated
	 */
	private String admissiontypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AdmitDateTime
	 * @mbggenerated
	 */
	private Date admitdatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AdmitSource
	 * @mbggenerated
	 */
	private String admitsource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AdmittingDoctor_Id
	 * @mbggenerated
	 */
	private String admittingdoctorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AdmittingDoctor_Name
	 * @mbggenerated
	 */
	private String admittingdoctorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AdmittingIntent
	 * @mbggenerated
	 */
	private String admittingintent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AssignedPatientLocation_Bed_Code
	 * @mbggenerated
	 */
	private String assignedpatientlocationBedCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AssignedPatientLocation_Bed_Name
	 * @mbggenerated
	 */
	private String assignedpatientlocationBedName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AssignedPatientLocation_LocationDescription_Code
	 * @mbggenerated
	 */
	private String assignedpatientlocationLocationdescriptionCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AssignedPatientLocation_LocationDescription_Name
	 * @mbggenerated
	 */
	private String assignedpatientlocationLocationdescriptionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AssignedPatientLocation_Room_Code
	 * @mbggenerated
	 */
	private String assignedpatientlocationRoomCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AssignedPatientLocation_Room_Name
	 * @mbggenerated
	 */
	private String assignedpatientlocationRoomName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AssignedPatientLocation_Ward_Code
	 * @mbggenerated
	 */
	private String assignedpatientlocationWardCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AssignedPatientLocation_Ward_Name
	 * @mbggenerated
	 */
	private String assignedpatientlocationWardName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AttendingDoctor_Id
	 * @mbggenerated
	 */
	private String attendingdoctorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.AttendingDoctor_Name
	 * @mbggenerated
	 */
	private String attendingdoctorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.BusinessPhone_IdentificationOfTheMedium
	 * @mbggenerated
	 */
	private String businessphoneIdentificationofthemedium;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.DeputyDoctor_Id
	 * @mbggenerated
	 */
	private String deputydoctorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.DeputyDoctor_Name
	 * @mbggenerated
	 */
	private String deputydoctorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.Director_Id
	 * @mbggenerated
	 */
	private String directorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.Director_Name
	 * @mbggenerated
	 */
	private String directorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.DoctorGroupId
	 * @mbggenerated
	 */
	private String doctorgroupid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.EmailAddress_IdentificationOfTheMedium
	 * @mbggenerated
	 */
	private String emailaddressIdentificationofthemedium;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.EncounterIdentifier_Id
	 * @mbggenerated
	 */
	private String encounteridentifierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.FinancialClass_Code
	 * @mbggenerated
	 */
	private String financialclassCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.FinancialClass_Name
	 * @mbggenerated
	 */
	private String financialclassName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.FirstAdmissionIndicator
	 * @mbggenerated
	 */
	private String firstadmissionindicator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.HomePhone_IdentificationOfTheMedium
	 * @mbggenerated
	 */
	private String homephoneIdentificationofthemedium;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.Insurance_InsuranceIdentifier_Id
	 * @mbggenerated
	 */
	private String insuranceInsuranceidentifierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.Insurance_InsuranceInformation
	 * @mbggenerated
	 */
	private String insuranceInsuranceinformation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.MailingAddress_AddressDescription
	 * @mbggenerated
	 */
	private String mailingaddressAddressdescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.MailingAddress_CityUrban
	 * @mbggenerated
	 */
	private String mailingaddressCityurban;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.MailingAddress_District
	 * @mbggenerated
	 */
	private String mailingaddressDistrict;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.MailingAddress_Number
	 * @mbggenerated
	 */
	private String mailingaddressNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.MailingAddress_PostalCode
	 * @mbggenerated
	 */
	private String mailingaddressPostalcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.MailingAddress_StateProvinceTerritory
	 * @mbggenerated
	 */
	private String mailingaddressStateprovinceterritory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.MailingAddress_StreetName
	 * @mbggenerated
	 */
	private String mailingaddressStreetname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.MailingAddress_SuburbTownLocality
	 * @mbggenerated
	 */
	private String mailingaddressSuburbtownlocality;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.MobilePhone_IdentificationOfTheMedium
	 * @mbggenerated
	 */
	private String mobilephoneIdentificationofthemedium;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.NursingClass
	 * @mbggenerated
	 */
	private String nursingclass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.NursingGroupId
	 * @mbggenerated
	 */
	private String nursinggroupid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.PatientClass_Code
	 * @mbggenerated
	 */
	private String patientclassCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.PatientClass_Name
	 * @mbggenerated
	 */
	private String patientclassName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.PatientCondition
	 * @mbggenerated
	 */
	private String patientcondition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.PatientIdentifier_Id
	 * @mbggenerated
	 */
	private String patientidentifierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.ResidentDoctor_Id
	 * @mbggenerated
	 */
	private String residentdoctorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.ResidentDoctor_Name
	 * @mbggenerated
	 */
	private String residentdoctorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.SpecialDepartment_Code
	 * @mbggenerated
	 */
	private String specialdepartmentCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.SpecialDepartment_Name
	 * @mbggenerated
	 */
	private String specialdepartmentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.Insurance_Type_Code
	 * @mbggenerated
	 */
	private String insuranceTypeCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.Insurance_Type_Name
	 * @mbggenerated
	 */
	private String insuranceTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.DoctorGrooupId
	 * @mbggenerated
	 */
	private String doctorgrooupid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.Insurance_Property_Code
	 * @mbggenerated
	 */
	private String insurancePropertyCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Admin_PatientAdmission.Insurance_Property_Name
	 * @mbggenerated
	 */
	private String insurancePropertyName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.Guid
	 * @return  the value of Admin_PatientAdmission.Guid
	 * @mbggenerated
	 */
	public String getGuid() {
		return guid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.Guid
	 * @param guid  the value for Admin_PatientAdmission.Guid
	 * @mbggenerated
	 */
	public void setGuid(String guid) {
		this.guid = guid == null ? null : guid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AdmissionType_Code
	 * @return  the value of Admin_PatientAdmission.AdmissionType_Code
	 * @mbggenerated
	 */
	public String getAdmissiontypeCode() {
		return admissiontypeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AdmissionType_Code
	 * @param admissiontypeCode  the value for Admin_PatientAdmission.AdmissionType_Code
	 * @mbggenerated
	 */
	public void setAdmissiontypeCode(String admissiontypeCode) {
		this.admissiontypeCode = admissiontypeCode == null ? null
				: admissiontypeCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AdmissionType_Name
	 * @return  the value of Admin_PatientAdmission.AdmissionType_Name
	 * @mbggenerated
	 */
	public String getAdmissiontypeName() {
		return admissiontypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AdmissionType_Name
	 * @param admissiontypeName  the value for Admin_PatientAdmission.AdmissionType_Name
	 * @mbggenerated
	 */
	public void setAdmissiontypeName(String admissiontypeName) {
		this.admissiontypeName = admissiontypeName == null ? null
				: admissiontypeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AdmitDateTime
	 * @return  the value of Admin_PatientAdmission.AdmitDateTime
	 * @mbggenerated
	 */
	public Date getAdmitdatetime() {
		return admitdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AdmitDateTime
	 * @param admitdatetime  the value for Admin_PatientAdmission.AdmitDateTime
	 * @mbggenerated
	 */
	public void setAdmitdatetime(Date admitdatetime) {
		this.admitdatetime = admitdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AdmitSource
	 * @return  the value of Admin_PatientAdmission.AdmitSource
	 * @mbggenerated
	 */
	public String getAdmitsource() {
		return admitsource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AdmitSource
	 * @param admitsource  the value for Admin_PatientAdmission.AdmitSource
	 * @mbggenerated
	 */
	public void setAdmitsource(String admitsource) {
		this.admitsource = admitsource == null ? null : admitsource.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AdmittingDoctor_Id
	 * @return  the value of Admin_PatientAdmission.AdmittingDoctor_Id
	 * @mbggenerated
	 */
	public String getAdmittingdoctorId() {
		return admittingdoctorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AdmittingDoctor_Id
	 * @param admittingdoctorId  the value for Admin_PatientAdmission.AdmittingDoctor_Id
	 * @mbggenerated
	 */
	public void setAdmittingdoctorId(String admittingdoctorId) {
		this.admittingdoctorId = admittingdoctorId == null ? null
				: admittingdoctorId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AdmittingDoctor_Name
	 * @return  the value of Admin_PatientAdmission.AdmittingDoctor_Name
	 * @mbggenerated
	 */
	public String getAdmittingdoctorName() {
		return admittingdoctorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AdmittingDoctor_Name
	 * @param admittingdoctorName  the value for Admin_PatientAdmission.AdmittingDoctor_Name
	 * @mbggenerated
	 */
	public void setAdmittingdoctorName(String admittingdoctorName) {
		this.admittingdoctorName = admittingdoctorName == null ? null
				: admittingdoctorName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AdmittingIntent
	 * @return  the value of Admin_PatientAdmission.AdmittingIntent
	 * @mbggenerated
	 */
	public String getAdmittingintent() {
		return admittingintent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AdmittingIntent
	 * @param admittingintent  the value for Admin_PatientAdmission.AdmittingIntent
	 * @mbggenerated
	 */
	public void setAdmittingintent(String admittingintent) {
		this.admittingintent = admittingintent == null ? null : admittingintent
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AssignedPatientLocation_Bed_Code
	 * @return  the value of Admin_PatientAdmission.AssignedPatientLocation_Bed_Code
	 * @mbggenerated
	 */
	public String getAssignedpatientlocationBedCode() {
		return assignedpatientlocationBedCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AssignedPatientLocation_Bed_Code
	 * @param assignedpatientlocationBedCode  the value for Admin_PatientAdmission.AssignedPatientLocation_Bed_Code
	 * @mbggenerated
	 */
	public void setAssignedpatientlocationBedCode(
			String assignedpatientlocationBedCode) {
		this.assignedpatientlocationBedCode = assignedpatientlocationBedCode == null ? null
				: assignedpatientlocationBedCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AssignedPatientLocation_Bed_Name
	 * @return  the value of Admin_PatientAdmission.AssignedPatientLocation_Bed_Name
	 * @mbggenerated
	 */
	public String getAssignedpatientlocationBedName() {
		return assignedpatientlocationBedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AssignedPatientLocation_Bed_Name
	 * @param assignedpatientlocationBedName  the value for Admin_PatientAdmission.AssignedPatientLocation_Bed_Name
	 * @mbggenerated
	 */
	public void setAssignedpatientlocationBedName(
			String assignedpatientlocationBedName) {
		this.assignedpatientlocationBedName = assignedpatientlocationBedName == null ? null
				: assignedpatientlocationBedName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AssignedPatientLocation_LocationDescription_Code
	 * @return  the value of Admin_PatientAdmission.AssignedPatientLocation_LocationDescription_Code
	 * @mbggenerated
	 */
	public String getAssignedpatientlocationLocationdescriptionCode() {
		return assignedpatientlocationLocationdescriptionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AssignedPatientLocation_LocationDescription_Code
	 * @param assignedpatientlocationLocationdescriptionCode  the value for Admin_PatientAdmission.AssignedPatientLocation_LocationDescription_Code
	 * @mbggenerated
	 */
	public void setAssignedpatientlocationLocationdescriptionCode(
			String assignedpatientlocationLocationdescriptionCode) {
		this.assignedpatientlocationLocationdescriptionCode = assignedpatientlocationLocationdescriptionCode == null ? null
				: assignedpatientlocationLocationdescriptionCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AssignedPatientLocation_LocationDescription_Name
	 * @return  the value of Admin_PatientAdmission.AssignedPatientLocation_LocationDescription_Name
	 * @mbggenerated
	 */
	public String getAssignedpatientlocationLocationdescriptionName() {
		return assignedpatientlocationLocationdescriptionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AssignedPatientLocation_LocationDescription_Name
	 * @param assignedpatientlocationLocationdescriptionName  the value for Admin_PatientAdmission.AssignedPatientLocation_LocationDescription_Name
	 * @mbggenerated
	 */
	public void setAssignedpatientlocationLocationdescriptionName(
			String assignedpatientlocationLocationdescriptionName) {
		this.assignedpatientlocationLocationdescriptionName = assignedpatientlocationLocationdescriptionName == null ? null
				: assignedpatientlocationLocationdescriptionName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AssignedPatientLocation_Room_Code
	 * @return  the value of Admin_PatientAdmission.AssignedPatientLocation_Room_Code
	 * @mbggenerated
	 */
	public String getAssignedpatientlocationRoomCode() {
		return assignedpatientlocationRoomCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AssignedPatientLocation_Room_Code
	 * @param assignedpatientlocationRoomCode  the value for Admin_PatientAdmission.AssignedPatientLocation_Room_Code
	 * @mbggenerated
	 */
	public void setAssignedpatientlocationRoomCode(
			String assignedpatientlocationRoomCode) {
		this.assignedpatientlocationRoomCode = assignedpatientlocationRoomCode == null ? null
				: assignedpatientlocationRoomCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AssignedPatientLocation_Room_Name
	 * @return  the value of Admin_PatientAdmission.AssignedPatientLocation_Room_Name
	 * @mbggenerated
	 */
	public String getAssignedpatientlocationRoomName() {
		return assignedpatientlocationRoomName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AssignedPatientLocation_Room_Name
	 * @param assignedpatientlocationRoomName  the value for Admin_PatientAdmission.AssignedPatientLocation_Room_Name
	 * @mbggenerated
	 */
	public void setAssignedpatientlocationRoomName(
			String assignedpatientlocationRoomName) {
		this.assignedpatientlocationRoomName = assignedpatientlocationRoomName == null ? null
				: assignedpatientlocationRoomName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AssignedPatientLocation_Ward_Code
	 * @return  the value of Admin_PatientAdmission.AssignedPatientLocation_Ward_Code
	 * @mbggenerated
	 */
	public String getAssignedpatientlocationWardCode() {
		return assignedpatientlocationWardCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AssignedPatientLocation_Ward_Code
	 * @param assignedpatientlocationWardCode  the value for Admin_PatientAdmission.AssignedPatientLocation_Ward_Code
	 * @mbggenerated
	 */
	public void setAssignedpatientlocationWardCode(
			String assignedpatientlocationWardCode) {
		this.assignedpatientlocationWardCode = assignedpatientlocationWardCode == null ? null
				: assignedpatientlocationWardCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AssignedPatientLocation_Ward_Name
	 * @return  the value of Admin_PatientAdmission.AssignedPatientLocation_Ward_Name
	 * @mbggenerated
	 */
	public String getAssignedpatientlocationWardName() {
		return assignedpatientlocationWardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AssignedPatientLocation_Ward_Name
	 * @param assignedpatientlocationWardName  the value for Admin_PatientAdmission.AssignedPatientLocation_Ward_Name
	 * @mbggenerated
	 */
	public void setAssignedpatientlocationWardName(
			String assignedpatientlocationWardName) {
		this.assignedpatientlocationWardName = assignedpatientlocationWardName == null ? null
				: assignedpatientlocationWardName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AttendingDoctor_Id
	 * @return  the value of Admin_PatientAdmission.AttendingDoctor_Id
	 * @mbggenerated
	 */
	public String getAttendingdoctorId() {
		return attendingdoctorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AttendingDoctor_Id
	 * @param attendingdoctorId  the value for Admin_PatientAdmission.AttendingDoctor_Id
	 * @mbggenerated
	 */
	public void setAttendingdoctorId(String attendingdoctorId) {
		this.attendingdoctorId = attendingdoctorId == null ? null
				: attendingdoctorId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.AttendingDoctor_Name
	 * @return  the value of Admin_PatientAdmission.AttendingDoctor_Name
	 * @mbggenerated
	 */
	public String getAttendingdoctorName() {
		return attendingdoctorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.AttendingDoctor_Name
	 * @param attendingdoctorName  the value for Admin_PatientAdmission.AttendingDoctor_Name
	 * @mbggenerated
	 */
	public void setAttendingdoctorName(String attendingdoctorName) {
		this.attendingdoctorName = attendingdoctorName == null ? null
				: attendingdoctorName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.BusinessPhone_IdentificationOfTheMedium
	 * @return  the value of Admin_PatientAdmission.BusinessPhone_IdentificationOfTheMedium
	 * @mbggenerated
	 */
	public String getBusinessphoneIdentificationofthemedium() {
		return businessphoneIdentificationofthemedium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.BusinessPhone_IdentificationOfTheMedium
	 * @param businessphoneIdentificationofthemedium  the value for Admin_PatientAdmission.BusinessPhone_IdentificationOfTheMedium
	 * @mbggenerated
	 */
	public void setBusinessphoneIdentificationofthemedium(
			String businessphoneIdentificationofthemedium) {
		this.businessphoneIdentificationofthemedium = businessphoneIdentificationofthemedium == null ? null
				: businessphoneIdentificationofthemedium.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.DeputyDoctor_Id
	 * @return  the value of Admin_PatientAdmission.DeputyDoctor_Id
	 * @mbggenerated
	 */
	public String getDeputydoctorId() {
		return deputydoctorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.DeputyDoctor_Id
	 * @param deputydoctorId  the value for Admin_PatientAdmission.DeputyDoctor_Id
	 * @mbggenerated
	 */
	public void setDeputydoctorId(String deputydoctorId) {
		this.deputydoctorId = deputydoctorId == null ? null : deputydoctorId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.DeputyDoctor_Name
	 * @return  the value of Admin_PatientAdmission.DeputyDoctor_Name
	 * @mbggenerated
	 */
	public String getDeputydoctorName() {
		return deputydoctorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.DeputyDoctor_Name
	 * @param deputydoctorName  the value for Admin_PatientAdmission.DeputyDoctor_Name
	 * @mbggenerated
	 */
	public void setDeputydoctorName(String deputydoctorName) {
		this.deputydoctorName = deputydoctorName == null ? null
				: deputydoctorName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.Director_Id
	 * @return  the value of Admin_PatientAdmission.Director_Id
	 * @mbggenerated
	 */
	public String getDirectorId() {
		return directorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.Director_Id
	 * @param directorId  the value for Admin_PatientAdmission.Director_Id
	 * @mbggenerated
	 */
	public void setDirectorId(String directorId) {
		this.directorId = directorId == null ? null : directorId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.Director_Name
	 * @return  the value of Admin_PatientAdmission.Director_Name
	 * @mbggenerated
	 */
	public String getDirectorName() {
		return directorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.Director_Name
	 * @param directorName  the value for Admin_PatientAdmission.Director_Name
	 * @mbggenerated
	 */
	public void setDirectorName(String directorName) {
		this.directorName = directorName == null ? null : directorName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.DoctorGroupId
	 * @return  the value of Admin_PatientAdmission.DoctorGroupId
	 * @mbggenerated
	 */
	public String getDoctorgroupid() {
		return doctorgroupid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.DoctorGroupId
	 * @param doctorgroupid  the value for Admin_PatientAdmission.DoctorGroupId
	 * @mbggenerated
	 */
	public void setDoctorgroupid(String doctorgroupid) {
		this.doctorgroupid = doctorgroupid == null ? null : doctorgroupid
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.EmailAddress_IdentificationOfTheMedium
	 * @return  the value of Admin_PatientAdmission.EmailAddress_IdentificationOfTheMedium
	 * @mbggenerated
	 */
	public String getEmailaddressIdentificationofthemedium() {
		return emailaddressIdentificationofthemedium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.EmailAddress_IdentificationOfTheMedium
	 * @param emailaddressIdentificationofthemedium  the value for Admin_PatientAdmission.EmailAddress_IdentificationOfTheMedium
	 * @mbggenerated
	 */
	public void setEmailaddressIdentificationofthemedium(
			String emailaddressIdentificationofthemedium) {
		this.emailaddressIdentificationofthemedium = emailaddressIdentificationofthemedium == null ? null
				: emailaddressIdentificationofthemedium.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.EncounterIdentifier_Id
	 * @return  the value of Admin_PatientAdmission.EncounterIdentifier_Id
	 * @mbggenerated
	 */
	public String getEncounteridentifierId() {
		return encounteridentifierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.EncounterIdentifier_Id
	 * @param encounteridentifierId  the value for Admin_PatientAdmission.EncounterIdentifier_Id
	 * @mbggenerated
	 */
	public void setEncounteridentifierId(String encounteridentifierId) {
		this.encounteridentifierId = encounteridentifierId == null ? null
				: encounteridentifierId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.FinancialClass_Code
	 * @return  the value of Admin_PatientAdmission.FinancialClass_Code
	 * @mbggenerated
	 */
	public String getFinancialclassCode() {
		return financialclassCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.FinancialClass_Code
	 * @param financialclassCode  the value for Admin_PatientAdmission.FinancialClass_Code
	 * @mbggenerated
	 */
	public void setFinancialclassCode(String financialclassCode) {
		this.financialclassCode = financialclassCode == null ? null
				: financialclassCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.FinancialClass_Name
	 * @return  the value of Admin_PatientAdmission.FinancialClass_Name
	 * @mbggenerated
	 */
	public String getFinancialclassName() {
		return financialclassName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.FinancialClass_Name
	 * @param financialclassName  the value for Admin_PatientAdmission.FinancialClass_Name
	 * @mbggenerated
	 */
	public void setFinancialclassName(String financialclassName) {
		this.financialclassName = financialclassName == null ? null
				: financialclassName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.FirstAdmissionIndicator
	 * @return  the value of Admin_PatientAdmission.FirstAdmissionIndicator
	 * @mbggenerated
	 */
	public String getFirstadmissionindicator() {
		return firstadmissionindicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.FirstAdmissionIndicator
	 * @param firstadmissionindicator  the value for Admin_PatientAdmission.FirstAdmissionIndicator
	 * @mbggenerated
	 */
	public void setFirstadmissionindicator(String firstadmissionindicator) {
		this.firstadmissionindicator = firstadmissionindicator == null ? null
				: firstadmissionindicator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.HomePhone_IdentificationOfTheMedium
	 * @return  the value of Admin_PatientAdmission.HomePhone_IdentificationOfTheMedium
	 * @mbggenerated
	 */
	public String getHomephoneIdentificationofthemedium() {
		return homephoneIdentificationofthemedium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.HomePhone_IdentificationOfTheMedium
	 * @param homephoneIdentificationofthemedium  the value for Admin_PatientAdmission.HomePhone_IdentificationOfTheMedium
	 * @mbggenerated
	 */
	public void setHomephoneIdentificationofthemedium(
			String homephoneIdentificationofthemedium) {
		this.homephoneIdentificationofthemedium = homephoneIdentificationofthemedium == null ? null
				: homephoneIdentificationofthemedium.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.Insurance_InsuranceIdentifier_Id
	 * @return  the value of Admin_PatientAdmission.Insurance_InsuranceIdentifier_Id
	 * @mbggenerated
	 */
	public String getInsuranceInsuranceidentifierId() {
		return insuranceInsuranceidentifierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.Insurance_InsuranceIdentifier_Id
	 * @param insuranceInsuranceidentifierId  the value for Admin_PatientAdmission.Insurance_InsuranceIdentifier_Id
	 * @mbggenerated
	 */
	public void setInsuranceInsuranceidentifierId(
			String insuranceInsuranceidentifierId) {
		this.insuranceInsuranceidentifierId = insuranceInsuranceidentifierId == null ? null
				: insuranceInsuranceidentifierId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.Insurance_InsuranceInformation
	 * @return  the value of Admin_PatientAdmission.Insurance_InsuranceInformation
	 * @mbggenerated
	 */
	public String getInsuranceInsuranceinformation() {
		return insuranceInsuranceinformation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.Insurance_InsuranceInformation
	 * @param insuranceInsuranceinformation  the value for Admin_PatientAdmission.Insurance_InsuranceInformation
	 * @mbggenerated
	 */
	public void setInsuranceInsuranceinformation(
			String insuranceInsuranceinformation) {
		this.insuranceInsuranceinformation = insuranceInsuranceinformation == null ? null
				: insuranceInsuranceinformation.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.MailingAddress_AddressDescription
	 * @return  the value of Admin_PatientAdmission.MailingAddress_AddressDescription
	 * @mbggenerated
	 */
	public String getMailingaddressAddressdescription() {
		return mailingaddressAddressdescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.MailingAddress_AddressDescription
	 * @param mailingaddressAddressdescription  the value for Admin_PatientAdmission.MailingAddress_AddressDescription
	 * @mbggenerated
	 */
	public void setMailingaddressAddressdescription(
			String mailingaddressAddressdescription) {
		this.mailingaddressAddressdescription = mailingaddressAddressdescription == null ? null
				: mailingaddressAddressdescription.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.MailingAddress_CityUrban
	 * @return  the value of Admin_PatientAdmission.MailingAddress_CityUrban
	 * @mbggenerated
	 */
	public String getMailingaddressCityurban() {
		return mailingaddressCityurban;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.MailingAddress_CityUrban
	 * @param mailingaddressCityurban  the value for Admin_PatientAdmission.MailingAddress_CityUrban
	 * @mbggenerated
	 */
	public void setMailingaddressCityurban(String mailingaddressCityurban) {
		this.mailingaddressCityurban = mailingaddressCityurban == null ? null
				: mailingaddressCityurban.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.MailingAddress_District
	 * @return  the value of Admin_PatientAdmission.MailingAddress_District
	 * @mbggenerated
	 */
	public String getMailingaddressDistrict() {
		return mailingaddressDistrict;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.MailingAddress_District
	 * @param mailingaddressDistrict  the value for Admin_PatientAdmission.MailingAddress_District
	 * @mbggenerated
	 */
	public void setMailingaddressDistrict(String mailingaddressDistrict) {
		this.mailingaddressDistrict = mailingaddressDistrict == null ? null
				: mailingaddressDistrict.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.MailingAddress_Number
	 * @return  the value of Admin_PatientAdmission.MailingAddress_Number
	 * @mbggenerated
	 */
	public String getMailingaddressNumber() {
		return mailingaddressNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.MailingAddress_Number
	 * @param mailingaddressNumber  the value for Admin_PatientAdmission.MailingAddress_Number
	 * @mbggenerated
	 */
	public void setMailingaddressNumber(String mailingaddressNumber) {
		this.mailingaddressNumber = mailingaddressNumber == null ? null
				: mailingaddressNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.MailingAddress_PostalCode
	 * @return  the value of Admin_PatientAdmission.MailingAddress_PostalCode
	 * @mbggenerated
	 */
	public String getMailingaddressPostalcode() {
		return mailingaddressPostalcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.MailingAddress_PostalCode
	 * @param mailingaddressPostalcode  the value for Admin_PatientAdmission.MailingAddress_PostalCode
	 * @mbggenerated
	 */
	public void setMailingaddressPostalcode(String mailingaddressPostalcode) {
		this.mailingaddressPostalcode = mailingaddressPostalcode == null ? null
				: mailingaddressPostalcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.MailingAddress_StateProvinceTerritory
	 * @return  the value of Admin_PatientAdmission.MailingAddress_StateProvinceTerritory
	 * @mbggenerated
	 */
	public String getMailingaddressStateprovinceterritory() {
		return mailingaddressStateprovinceterritory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.MailingAddress_StateProvinceTerritory
	 * @param mailingaddressStateprovinceterritory  the value for Admin_PatientAdmission.MailingAddress_StateProvinceTerritory
	 * @mbggenerated
	 */
	public void setMailingaddressStateprovinceterritory(
			String mailingaddressStateprovinceterritory) {
		this.mailingaddressStateprovinceterritory = mailingaddressStateprovinceterritory == null ? null
				: mailingaddressStateprovinceterritory.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.MailingAddress_StreetName
	 * @return  the value of Admin_PatientAdmission.MailingAddress_StreetName
	 * @mbggenerated
	 */
	public String getMailingaddressStreetname() {
		return mailingaddressStreetname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.MailingAddress_StreetName
	 * @param mailingaddressStreetname  the value for Admin_PatientAdmission.MailingAddress_StreetName
	 * @mbggenerated
	 */
	public void setMailingaddressStreetname(String mailingaddressStreetname) {
		this.mailingaddressStreetname = mailingaddressStreetname == null ? null
				: mailingaddressStreetname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.MailingAddress_SuburbTownLocality
	 * @return  the value of Admin_PatientAdmission.MailingAddress_SuburbTownLocality
	 * @mbggenerated
	 */
	public String getMailingaddressSuburbtownlocality() {
		return mailingaddressSuburbtownlocality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.MailingAddress_SuburbTownLocality
	 * @param mailingaddressSuburbtownlocality  the value for Admin_PatientAdmission.MailingAddress_SuburbTownLocality
	 * @mbggenerated
	 */
	public void setMailingaddressSuburbtownlocality(
			String mailingaddressSuburbtownlocality) {
		this.mailingaddressSuburbtownlocality = mailingaddressSuburbtownlocality == null ? null
				: mailingaddressSuburbtownlocality.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.MobilePhone_IdentificationOfTheMedium
	 * @return  the value of Admin_PatientAdmission.MobilePhone_IdentificationOfTheMedium
	 * @mbggenerated
	 */
	public String getMobilephoneIdentificationofthemedium() {
		return mobilephoneIdentificationofthemedium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.MobilePhone_IdentificationOfTheMedium
	 * @param mobilephoneIdentificationofthemedium  the value for Admin_PatientAdmission.MobilePhone_IdentificationOfTheMedium
	 * @mbggenerated
	 */
	public void setMobilephoneIdentificationofthemedium(
			String mobilephoneIdentificationofthemedium) {
		this.mobilephoneIdentificationofthemedium = mobilephoneIdentificationofthemedium == null ? null
				: mobilephoneIdentificationofthemedium.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.NursingClass
	 * @return  the value of Admin_PatientAdmission.NursingClass
	 * @mbggenerated
	 */
	public String getNursingclass() {
		return nursingclass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.NursingClass
	 * @param nursingclass  the value for Admin_PatientAdmission.NursingClass
	 * @mbggenerated
	 */
	public void setNursingclass(String nursingclass) {
		this.nursingclass = nursingclass == null ? null : nursingclass.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.NursingGroupId
	 * @return  the value of Admin_PatientAdmission.NursingGroupId
	 * @mbggenerated
	 */
	public String getNursinggroupid() {
		return nursinggroupid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.NursingGroupId
	 * @param nursinggroupid  the value for Admin_PatientAdmission.NursingGroupId
	 * @mbggenerated
	 */
	public void setNursinggroupid(String nursinggroupid) {
		this.nursinggroupid = nursinggroupid == null ? null : nursinggroupid
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.PatientClass_Code
	 * @return  the value of Admin_PatientAdmission.PatientClass_Code
	 * @mbggenerated
	 */
	public String getPatientclassCode() {
		return patientclassCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.PatientClass_Code
	 * @param patientclassCode  the value for Admin_PatientAdmission.PatientClass_Code
	 * @mbggenerated
	 */
	public void setPatientclassCode(String patientclassCode) {
		this.patientclassCode = patientclassCode == null ? null
				: patientclassCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.PatientClass_Name
	 * @return  the value of Admin_PatientAdmission.PatientClass_Name
	 * @mbggenerated
	 */
	public String getPatientclassName() {
		return patientclassName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.PatientClass_Name
	 * @param patientclassName  the value for Admin_PatientAdmission.PatientClass_Name
	 * @mbggenerated
	 */
	public void setPatientclassName(String patientclassName) {
		this.patientclassName = patientclassName == null ? null
				: patientclassName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.PatientCondition
	 * @return  the value of Admin_PatientAdmission.PatientCondition
	 * @mbggenerated
	 */
	public String getPatientcondition() {
		return patientcondition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.PatientCondition
	 * @param patientcondition  the value for Admin_PatientAdmission.PatientCondition
	 * @mbggenerated
	 */
	public void setPatientcondition(String patientcondition) {
		this.patientcondition = patientcondition == null ? null
				: patientcondition.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.PatientIdentifier_Id
	 * @return  the value of Admin_PatientAdmission.PatientIdentifier_Id
	 * @mbggenerated
	 */
	public String getPatientidentifierId() {
		return patientidentifierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.PatientIdentifier_Id
	 * @param patientidentifierId  the value for Admin_PatientAdmission.PatientIdentifier_Id
	 * @mbggenerated
	 */
	public void setPatientidentifierId(String patientidentifierId) {
		this.patientidentifierId = patientidentifierId == null ? null
				: patientidentifierId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.ResidentDoctor_Id
	 * @return  the value of Admin_PatientAdmission.ResidentDoctor_Id
	 * @mbggenerated
	 */
	public String getResidentdoctorId() {
		return residentdoctorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.ResidentDoctor_Id
	 * @param residentdoctorId  the value for Admin_PatientAdmission.ResidentDoctor_Id
	 * @mbggenerated
	 */
	public void setResidentdoctorId(String residentdoctorId) {
		this.residentdoctorId = residentdoctorId == null ? null
				: residentdoctorId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.ResidentDoctor_Name
	 * @return  the value of Admin_PatientAdmission.ResidentDoctor_Name
	 * @mbggenerated
	 */
	public String getResidentdoctorName() {
		return residentdoctorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.ResidentDoctor_Name
	 * @param residentdoctorName  the value for Admin_PatientAdmission.ResidentDoctor_Name
	 * @mbggenerated
	 */
	public void setResidentdoctorName(String residentdoctorName) {
		this.residentdoctorName = residentdoctorName == null ? null
				: residentdoctorName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.SpecialDepartment_Code
	 * @return  the value of Admin_PatientAdmission.SpecialDepartment_Code
	 * @mbggenerated
	 */
	public String getSpecialdepartmentCode() {
		return specialdepartmentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.SpecialDepartment_Code
	 * @param specialdepartmentCode  the value for Admin_PatientAdmission.SpecialDepartment_Code
	 * @mbggenerated
	 */
	public void setSpecialdepartmentCode(String specialdepartmentCode) {
		this.specialdepartmentCode = specialdepartmentCode == null ? null
				: specialdepartmentCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.SpecialDepartment_Name
	 * @return  the value of Admin_PatientAdmission.SpecialDepartment_Name
	 * @mbggenerated
	 */
	public String getSpecialdepartmentName() {
		return specialdepartmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.SpecialDepartment_Name
	 * @param specialdepartmentName  the value for Admin_PatientAdmission.SpecialDepartment_Name
	 * @mbggenerated
	 */
	public void setSpecialdepartmentName(String specialdepartmentName) {
		this.specialdepartmentName = specialdepartmentName == null ? null
				: specialdepartmentName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.Insurance_Type_Code
	 * @return  the value of Admin_PatientAdmission.Insurance_Type_Code
	 * @mbggenerated
	 */
	public String getInsuranceTypeCode() {
		return insuranceTypeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.Insurance_Type_Code
	 * @param insuranceTypeCode  the value for Admin_PatientAdmission.Insurance_Type_Code
	 * @mbggenerated
	 */
	public void setInsuranceTypeCode(String insuranceTypeCode) {
		this.insuranceTypeCode = insuranceTypeCode == null ? null
				: insuranceTypeCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.Insurance_Type_Name
	 * @return  the value of Admin_PatientAdmission.Insurance_Type_Name
	 * @mbggenerated
	 */
	public String getInsuranceTypeName() {
		return insuranceTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.Insurance_Type_Name
	 * @param insuranceTypeName  the value for Admin_PatientAdmission.Insurance_Type_Name
	 * @mbggenerated
	 */
	public void setInsuranceTypeName(String insuranceTypeName) {
		this.insuranceTypeName = insuranceTypeName == null ? null
				: insuranceTypeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.DoctorGrooupId
	 * @return  the value of Admin_PatientAdmission.DoctorGrooupId
	 * @mbggenerated
	 */
	public String getDoctorgrooupid() {
		return doctorgrooupid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.DoctorGrooupId
	 * @param doctorgrooupid  the value for Admin_PatientAdmission.DoctorGrooupId
	 * @mbggenerated
	 */
	public void setDoctorgrooupid(String doctorgrooupid) {
		this.doctorgrooupid = doctorgrooupid == null ? null : doctorgrooupid
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.Insurance_Property_Code
	 * @return  the value of Admin_PatientAdmission.Insurance_Property_Code
	 * @mbggenerated
	 */
	public String getInsurancePropertyCode() {
		return insurancePropertyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.Insurance_Property_Code
	 * @param insurancePropertyCode  the value for Admin_PatientAdmission.Insurance_Property_Code
	 * @mbggenerated
	 */
	public void setInsurancePropertyCode(String insurancePropertyCode) {
		this.insurancePropertyCode = insurancePropertyCode == null ? null
				: insurancePropertyCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Admin_PatientAdmission.Insurance_Property_Name
	 * @return  the value of Admin_PatientAdmission.Insurance_Property_Name
	 * @mbggenerated
	 */
	public String getInsurancePropertyName() {
		return insurancePropertyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Admin_PatientAdmission.Insurance_Property_Name
	 * @param insurancePropertyName  the value for Admin_PatientAdmission.Insurance_Property_Name
	 * @mbggenerated
	 */
	public void setInsurancePropertyName(String insurancePropertyName) {
		this.insurancePropertyName = insurancePropertyName == null ? null
				: insurancePropertyName.trim();
	}
}