package com.test.mybatis.dao;

import com.test.mybatis.model.OrderExecutePaper;

public interface OrderExecutePaperMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Inst_OrderExcute
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Inst_OrderExcute
	 * @mbggenerated
	 */
	int insert(OrderExecutePaper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Inst_OrderExcute
	 * @mbggenerated
	 */
	int insertSelective(OrderExecutePaper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Inst_OrderExcute
	 * @mbggenerated
	 */
	OrderExecutePaper selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Inst_OrderExcute
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(OrderExecutePaper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Inst_OrderExcute
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OrderExecutePaper record);
}