package com.test.mybatis.dao;

import com.test.mybatis.model.PatientDischargeInfo;

public interface PatientDischargeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Admin_DischargeAdministrativeInformation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Admin_DischargeAdministrativeInformation
     *
     * @mbggenerated
     */
    int insert(PatientDischargeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Admin_DischargeAdministrativeInformation
     *
     * @mbggenerated
     */
    int insertSelective(PatientDischargeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Admin_DischargeAdministrativeInformation
     *
     * @mbggenerated
     */
    PatientDischargeInfo selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Admin_DischargeAdministrativeInformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PatientDischargeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Admin_DischargeAdministrativeInformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PatientDischargeInfo record);
}