package com.test.mybatis.dao;

import com.test.mybatis.model.PatientADTInfo;

public interface PatientADTInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Admin_Transaction
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Admin_Transaction
	 * @mbggenerated
	 */
	int insert(PatientADTInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Admin_Transaction
	 * @mbggenerated
	 */
	int insertSelective(PatientADTInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Admin_Transaction
	 * @mbggenerated
	 */
	PatientADTInfo selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Admin_Transaction
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PatientADTInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Admin_Transaction
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PatientADTInfo record);
}